.TH __FIND_SUBSTRATE_ID 1 2025-Jul "" "__find_substrate_id"
.SH NAME
__find_substrate_id \- __find_substrate_id(args, xrefs)
.SH SYNOPSIS
\fI__find_substrate_id(args, xrefs)\fR
.SH OPTIONS
.PP
\fBargs\fB \fR\- . 
.PP
.PP
\fBxrefs\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__find_substrate_id at sabiork.R:line 115
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
