.TH __PUSH_COMPOUND_METADATA 1 2024-Aug "" "__push_compound_metadata"
.SH NAME
__push_compound_metadata \- __push_compound_metadata(biocad.registry, compound, mol)
.SH SYNOPSIS
\fI__push_compound_metadata(biocad.registry, compound, mol)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.PP
\fBcompound\fB \fR\- . 
.PP
.PP
\fBmol\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__push_compound_metadata at pubchem.R:line 54
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2024
