.TH CAST_KEGG_REACTION 1 2025-Jun "" "cast_kegg_reaction"
.SH NAME
cast_kegg_reaction \- cast_kegg_reaction(rxn)
.SH SYNOPSIS
\fIcast_kegg_reaction(rxn)\fR
.SH OPTIONS
.PP
\fBrxn\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.cast_kegg_reaction at kegg.R:line 130
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
