.TH CHECK_METABOLITE 1 2025-May "" "check of the metabolite is existsed inside database"
.SH NAME
check_metabolite \- check_metabolite(biocad.registry, compound)
.SH SYNOPSIS
\fIcheck_metabolite(biocad.registry, compound)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.PP
\fBcompound\fB \fR\- . 
.PP
.SH VALUE
.PP
an integer unique id of the compound that matched with the compound xrefs information, NULL will be returns if the molecule metabolite data has not been found.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.check_metabolite at check_metabolite.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
