.TH CHECK_METABOLITE_SYNONYM 1 2025-May "" "check_metabolite_synonym"
.SH NAME
check_metabolite_synonym \- check_metabolite_synonym(biocad.registry, compound)
.SH SYNOPSIS
\fIcheck_metabolite_synonym(biocad.registry, compound)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.PP
\fBcompound\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.check_metabolite_synonym at check_metabolite.R:line 55
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
