.TH ENZYME_REGULATION 1 2025-Mar "" "enzyme_regulation"
.SH NAME
enzyme_regulation \- enzyme_regulation(biocad.registry)
.SH SYNOPSIS
\fIenzyme_regulation(biocad.registry)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.enzyme_regulation at biocad_registry.R:line 37
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
