.TH EXPORT_REACTIONLINKS 1 2025-Jul "" "export_reactionLinks"
.SH NAME
export_reactionLinks \- export_reactionLinks(biocad.registry)
.SH SYNOPSIS
\fIexport_reactionLinks(biocad.registry)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.export_reactionLinks at reaction_links.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
