.TH EXPORT_ENZYMATIC 1 2025-Jun "" "export_enzymatic"
.SH NAME
export_enzymatic \- export_enzymatic(biocad.registry)
.SH SYNOPSIS
\fIexport_enzymatic(biocad.registry)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.export_enzymatic at enzyme_km.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
