.TH EXPORT_GENOMICS_FASTA 1 2025-Dec "" "export_genomics_fasta"
.SH NAME
export_genomics_fasta \- export_genomics_fasta(biocad.registry, parent.taxname,
    <i>fasta</i> = <span style='color: blue !important;'>TRUE</span>)
.SH SYNOPSIS
\fIexport_genomics_fasta(biocad.registry, parent.taxname,
    <i>fasta</i> = <span style='color: blue !important;'>TRUE</span>)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.PP
\fBparent.taxname\fB \fR\- . 
.PP
.PP
\fBfasta\fB \fR\- TRUE. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.export_genomics_fasta at genomics.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
