.TH FIND_MOLECULE 1 2025-Feb "" "A common function for find a target metabolite molecule"
.SH NAME
find_molecule \- find_molecule(biocad.registry, meta, xref.id)
.SH SYNOPSIS
\fIfind_molecule(biocad.registry, meta, xref.id)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.PP
\fBmeta\fB \fR\- . 
.PP
.PP
\fBxref.id\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.find_molecule at find_molecule.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
