.TH GENE_TERM 1 2025-Jun "" "get vocabulary term id of ``Nucleic Acid``"
.SH NAME
gene_term \- gene_term(biocad.registry)
.SH SYNOPSIS
\fIgene_term(biocad.registry)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.gene_term at biocad_registry.R:line 2
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
