.TH GET_GENBANK_FTP 1 2025-Nov "" "get_genbank_ftp"
.SH NAME
get_genbank_ftp \- get_genbank_ftp(ncbi, url,
    <i>repo.dir</i> = <span style='color: brown;'><strong>'./'</strong></span>)
.SH SYNOPSIS
\fIget_genbank_ftp(ncbi, url,
    <i>repo.dir</i> = <span style='color: brown;'><strong>'./'</strong></span>)\fR
.SH OPTIONS
.PP
\fBncbi\fB \fR\- . 
.PP
.PP
\fBurl\fB \fR\- . 
.PP
.PP
\fBrepo.dir\fB \fR\- './'. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.get_genbank_ftp at ncbi_ftp.R:line 65
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
