.TH GET_MOTIF_SITES 1 2023-May "" "Export motif sites from the biocad registry"
.SH NAME
get_motif_sites \- get_motif_sites(family,
    <i>fasta</i> = <span style='color: blue;'>FALSE</span>)
.SH SYNOPSIS
\fIget_motif_sites(family,
    <i>fasta</i> = <span style='color: blue;'>FALSE</span>)\fR
.SH OPTIONS
.PP
\fBfamily\fB \fR\- . A specific motif family for export data
.PP
.PP
\fBfasta\fB \fR\- FALSE. this parameter affect the return value is a dataframe or fasta collection object
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.get_motif_sites at exports.R:line 14
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2023
