.TH GET_DBLINKS 1 2024-Apr "" "get_dblinks"
.SH NAME
get_dblinks \- get_dblinks(dbname,
    <i>page</i> = <span style='color: green;'>1</span>,
    <i>page.size</i> = <span style='color: green;'>1000</span>)
.SH SYNOPSIS
\fIget_dblinks(dbname,
    <i>page</i> = <span style='color: green;'>1</span>,
    <i>page.size</i> = <span style='color: green;'>1000</span>)\fR
.SH OPTIONS
.PP
\fBdbname\fB \fR\- . 
.PP
.PP
\fBpage\fB \fR\- 1. 
.PP
.PP
\fBpage.size\fB \fR\- 1000. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.get_dblinks at exports.R:line 49
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2024
