.TH GET_MOLECULE_BY_DBXREF 1 2024-Dec "" "Get molecule id via a specific database cross reference link id"
.SH NAME
get_molecule_by_dbxref \- get_molecule_by_dbxref(registry, db.xref,
    <i>dbname</i> = <span style='color: blue !important;'>NULL</span>)
.SH SYNOPSIS
\fIget_molecule_by_dbxref(registry, db.xref,
    <i>dbname</i> = <span style='color: blue !important;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBregistry\fB \fR\- . 
.PP
.PP
\fBdb.xref\fB \fR\- . 
.PP
.PP
\fBdbname\fB \fR\- NULL. 
.PP
.SH VALUE
.PP
an integer id of the target molecule, NULL when object not found.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.get_molecule_by_dbxref at link.R:line 5
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2024
