.TH IMPORTS_CHEBI 1 2025-Feb "" "imports the metabolite set from chebi database"
.SH NAME
imports_chebi \- imports_chebi(biocad.registry, chebi)
.SH SYNOPSIS
\fIimports_chebi(biocad.registry, chebi)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.PP
\fBchebi\fB \fR\- . the chebi ontology OBO database, the metabolite compound data will be extract from this database obejct.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.imports_chebi at chebi.R:line 8
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
