.TH IMPORTS_KEGG 1 2025-Feb "" "imports kegg compound into data repository"
.SH NAME
imports_kegg \- imports_kegg(biocad.registry, kegg)
.SH SYNOPSIS
\fIimports_kegg(biocad.registry, kegg)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.PP
\fBkegg\fB \fR\- . a kegg compound collection
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.imports_kegg at kegg.R:line 5
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
