.TH IMPORTS_KEGG_REACTION 1 2024-Dec "" "imports_kegg_reaction"
.SH NAME
imports_kegg_reaction \- imports_kegg_reaction(biocad.registry, kegg)
.SH SYNOPSIS
\fIimports_kegg_reaction(biocad.registry, kegg)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.PP
\fBkegg\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.imports_kegg_reaction at kegg.R:line 61
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2024
