.TH IMPORTS_RHEA 1 2025-May "" "imports the rhea reaction database"
.SH NAME
imports_rhea \- imports_rhea(biocad.registry, rhea)
.SH SYNOPSIS
\fIimports_rhea(biocad.registry, rhea)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.PP
\fBrhea\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.imports_rhea at rhea.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
