.TH IMPORTS_CHEBI 1 2024-Aug "" "imports the metabolite set from chebi database"
.SH NAME
imports_chebi \- imports_chebi(biocad.registry, chebi)
.SH SYNOPSIS
\fIimports_chebi(biocad.registry, chebi)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.PP
\fBchebi\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.imports_chebi at chebi.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2024
