.TH IMPORTS_GENEBANK 1 2024-Aug "" "imports_genebank"
.SH NAME
imports_genebank \- imports_genebank(biocad.registry, genebank)
.SH SYNOPSIS
\fIimports_genebank(biocad.registry, genebank)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.PP
\fBgenebank\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.imports_genebank at genbank.R:line 2
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2024
