.TH IMPORTS_GENOMIC_REFSEQ 1 2025-May "" "imports_genomic_refseq"
.SH NAME
imports_genomic_refseq \- imports_genomic_refseq(biocad.registry, gbff)
.SH SYNOPSIS
\fIimports_genomic_refseq(biocad.registry, gbff)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.PP
\fBgbff\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.imports_genomic_refseq at genomic.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
