.TH IMPORTS_RHEA 1 2025-Dec "" "imports_rhea"
.SH NAME
imports_rhea \- imports_rhea(biocad.registry,
    <i>rhea</i> = <span style='color: brown;'><strong>'./rhea.rdf'</strong></span>)
.SH SYNOPSIS
\fIimports_rhea(biocad.registry,
    <i>rhea</i> = <span style='color: brown;'><strong>'./rhea.rdf'</strong></span>)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.PP
\fBrhea\fB \fR\- './rhea.rdf'. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.imports_rhea at rhea.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
