.TH IMPORTS_METACYC 1 2024-Nov "" "helper function for imports the metacyc molecules and reactions"
.SH NAME
imports_metacyc \- imports_metacyc()
.SH SYNOPSIS
\fIimports_metacyc()\fR
.SH FILES
.PP
SMRUCC/R#.declare_function.imports_metacyc at metacyc.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2024
