.TH IMPORTS_UNIPROT 1 2025-Feb "" "helper function for imports uniprot proteins"
.SH NAME
imports_uniprot \- imports_uniprot(biocad.registry, uniprot,
    <i>fast.check</i> = <span style='color: blue !important;'>FALSE</span>)
.SH SYNOPSIS
\fIimports_uniprot(biocad.registry, uniprot,
    <i>fast.check</i> = <span style='color: blue !important;'>FALSE</span>)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.PP
\fBuniprot\fB \fR\- . 
.PP
.PP
\fBfast.check\fB \fR\- FALSE. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.imports_uniprot at uniprot.R:line 9
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
