.TH IMPORTS_GENEBANK.OBSOLETE 1 2026-Feb "" "imports gene from ncbi genbank file"
.SH NAME
imports_genebank.obsolete \- imports_genebank.obsolete(biocad.registry, genebank)
.SH SYNOPSIS
\fIimports_genebank.obsolete(biocad.registry, genebank)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.PP
\fBgenebank\fB \fR\- . A ncbi genebank data object, all CDS/rna features inside
this genebank data object will be extract and imports into
database.
.PP
.SH DETAILS
.PP
this function will make association between the gene/rna
and uniprot protein molecules.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.imports_genebank.obsolete at genbank.R:line 12
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2026
