.TH IMPORTS_ODOR 1 2024-Dec "" "imports_odor"
.SH NAME
imports_odor \- imports_odor(biocad.registry, pubchem)
.SH SYNOPSIS
\fIimports_odor(biocad.registry, pubchem)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.PP
\fBpubchem\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.imports_odor at pubchem.R:line 39
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2024
