.TH IMPORTS_SABIORK 1 2025-Feb "" "imports enzymatic kinetics model"
.SH NAME
imports_sabiork \- imports_sabiork(biocad.registry, repo)
.SH SYNOPSIS
\fIimports_sabiork(biocad.registry, repo)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.PP
\fBrepo\fB \fR\- . a character vector of the xml data files for the enzymatic kinetics data
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.imports_sabiork at sabiork.R:line 5
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
