.TH IMPORTS_PUBCHEM 1 2026-Feb "" "imports_pubchem"
.SH NAME
imports_pubchem \- imports_pubchem(biocad.registry, pubchem)
.SH SYNOPSIS
\fIimports_pubchem(biocad.registry, pubchem)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.PP
\fBpubchem\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.imports_pubchem at pubchem.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2026
