.TH LINK_REACTION_METABOLITES 1 2026-Jan "" "link_reaction_metabolites"
.SH NAME
link_reaction_metabolites \- link_reaction_metabolites(biocad.registry,
    <i>refresh</i> = <span style='color: blue !important;'>FALSE</span>)
.SH SYNOPSIS
\fIlink_reaction_metabolites(biocad.registry,
    <i>refresh</i> = <span style='color: blue !important;'>FALSE</span>)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.PP
\fBrefresh\fB \fR\- FALSE. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.link_reaction_metabolites at link_reaction_metabolites.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2026
