.TH LINK_GENE_PROTEINS 1 2025-Jun "" "Link the gene and protein parent/child relationship"
.SH NAME
link_gene_proteins \- link_gene_proteins(biocad.registry)
.SH SYNOPSIS
\fIlink_gene_proteins(biocad.registry)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.link_gene_proteins at link_gene_proteins.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
