.TH LINK_GENE_PROTEINS 1 2025-Apr "" "Link the gene and protein parent/child relationship"
.SH NAME
link_gene_proteins \- link_gene_proteins(biocad.registry)
.SH SYNOPSIS
\fIlink_gene_proteins(biocad.registry)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.SH DETAILS
.PP
probabily there is no needs for links the protein back to its source gene object, due to the reason of gene sequence could be reverse translates from the protein sequence.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.link_gene_proteins at link_gene_proteins.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
