.TH LINK_KINETICS 1 2025-Aug "" "link the kinetics law with the enzyme and metabolite substrate molecules"
.SH NAME
link_kinetics \- link_kinetics(registry)
.SH SYNOPSIS
\fIlink_kinetics(registry)\fR
.SH OPTIONS
.PP
\fBregistry\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.link_kinetics at link_kinetics.R:line 5
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
