.TH LINK_REACTION_METABOLITES 1 2025-Oct "" "link_reaction_metabolites"
.SH NAME
link_reaction_metabolites \- link_reaction_metabolites(biocad.registry)
.SH SYNOPSIS
\fIlink_reaction_metabolites(biocad.registry)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.link_reaction_metabolites at link_reaction_metabolites.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
