.TH LINK_REACTION_ENZYMES 1 2026-Feb "" "link_reaction_enzymes"
.SH NAME
link_reaction_enzymes \- link_reaction_enzymes(biocad.registry)
.SH SYNOPSIS
\fIlink_reaction_enzymes(biocad.registry)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.link_reaction_enzymes at link_reaction_enzymes.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2026
