.TH LOAD_BIOCYC_PROTEINS 1 2025-Sep "" "load_biocyc_proteins"
.SH NAME
load_biocyc_proteins \- load_biocyc_proteins(biocad.registry, metacyc)
.SH SYNOPSIS
\fIload_biocyc_proteins(biocad.registry, metacyc)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.PP
\fBmetacyc\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.load_biocyc_proteins at metacyc.R:line 14
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
