.TH LOAD_BIOCYC_REACTIONS 1 2026-Jan "" "load_biocyc_reactions"
.SH NAME
load_biocyc_reactions \- load_biocyc_reactions(biocad.registry, metacyc)
.SH SYNOPSIS
\fIload_biocyc_reactions(biocad.registry, metacyc)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.PP
\fBmetacyc\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.load_biocyc_reactions at metacyc.R:line 213
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2026
