.TH LOAD_BIOCYC_GENES 1 2025-Feb "" "load_biocyc_genes"
.SH NAME
load_biocyc_genes \- load_biocyc_genes(biocad.registry, metacyc)
.SH SYNOPSIS
\fIload_biocyc_genes(biocad.registry, metacyc)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.PP
\fBmetacyc\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.load_biocyc_genes at metacyc.R:line 130
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
