.TH LOAD_BIOCYC_COMPOUNDS 1 2024-Nov "" "load and imports compounds from the metacyc database"
.SH NAME
load_biocyc_compounds \- load_biocyc_compounds(biocad.registry, metacyc)
.SH SYNOPSIS
\fIload_biocyc_compounds(biocad.registry, metacyc)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.PP
\fBmetacyc\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.load_biocyc_compounds at metacyc.R:line 83
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2024
