.TH METABOLITE_TERM 1 2025-Jun "" "get vocabulary term id of ``Metabolite``"
.SH NAME
metabolite_term \- metabolite_term(biocad.registry)
.SH SYNOPSIS
\fImetabolite_term(biocad.registry)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.metabolite_term at biocad_registry.R:line 17
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
