.TH MOLECULE_ENTITY 1 2025-May "" "the molecule entity term"
.SH NAME
molecule_entity \- molecule_entity(biocad.registry)
.SH SYNOPSIS
\fImolecule_entity(biocad.registry)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.SH DETAILS
.PP
the "Nucleic Acid", "RNA", "Polypeptide", "Metabolite" is belong to the molecule entity object.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.molecule_entity at biocad_registry.R:line 32
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
