.TH MOLECULE_TERMS 1 2025-Aug "" "get vocabulary term id collection of multiple molecule types"
.SH NAME
molecule_terms \- molecule_terms(biocad.registry)
.SH SYNOPSIS
\fImolecule_terms(biocad.registry)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.molecule_terms at biocad_registry.R:line 25
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
