.TH OPEN_REGISTRY 1 2025-Mar "" "open mysqli connection to biocad_registry"
.SH NAME
open_registry \- open_registry(user, passwd,
    <i>host</i> = <span style='color: brown;'><strong>'localhost'</strong></span>,
    <i>port</i> = <span style='color: green;'>3306</span>,
    <i>dbname</i> = <span style='color: brown;'><strong>'cad_registry'</strong></span>)
.SH SYNOPSIS
\fIopen_registry(user, passwd,
    <i>host</i> = <span style='color: brown;'><strong>'localhost'</strong></span>,
    <i>port</i> = <span style='color: green;'>3306</span>,
    <i>dbname</i> = <span style='color: brown;'><strong>'cad_registry'</strong></span>)\fR
.SH OPTIONS
.PP
\fBuser\fB \fR\- . 
.PP
.PP
\fBpasswd\fB \fR\- . 
.PP
.PP
\fBhost\fB \fR\- 'localhost'. the mysql server host
.PP
.PP
\fBport\fB \fR\- 3306. 
.PP
.PP
\fBdbname\fB \fR\- 'cad_registry'. the database name of the target mysql database, value may be ``cad_registry`` or ``biocad_registry``.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.open_registry at mysql.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
