.TH PROTEIN_TERM 1 2025-Nov "" "protein_term"
.SH NAME
protein_term \- protein_term(biocad.registry)
.SH SYNOPSIS
\fIprotein_term(biocad.registry)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.protein_term at biocad_registry.R:line 12
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
