.TH PULL_MOTIF_FAMILY 1 2023-May "" "Fetch all motif family"
.SH NAME
pull_motif_family \- pull_motif_family(
    <i>genome.id</i> = <span style='color: blue;'>NULL</span>)
.SH SYNOPSIS
\fIpull_motif_family(
    <i>genome.id</i> = <span style='color: blue;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBgenome.id\fB \fR\- NULL. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.pull_motif_family at pull.R:line 21
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2023
