.TH PULL_TAXONOMIC 1 2024-Apr "" "pull_taxonomic"
.SH NAME
pull_taxonomic \- pull_taxonomic(
    <i>id</i> = <span style='color: blue !important;'>NULL</span>)
.SH SYNOPSIS
\fIpull_taxonomic(
    <i>id</i> = <span style='color: blue !important;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBid\fB \fR\- NULL. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.pull_taxonomic at pull.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2024
