.TH PUT.REGULATION 1 2023-Jun "" "put.regulation"
.SH NAME
put.regulation \- put.regulation(genome.id, regulator, family, type, sites)
.SH SYNOPSIS
\fIput.regulation(genome.id, regulator, family, type, sites)\fR
.SH OPTIONS
.PP
\fBgenome.id\fB \fR\- . 
.PP
.PP
\fBregulator\fB \fR\- . 
.PP
.PP
\fBfamily\fB \fR\- . 
.PP
.PP
\fBtype\fB \fR\- . 
.PP
.PP
\fBsites\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.put.regulation at put.R:line 49
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2023
