.TH PUT.TAXONOMIC_GROUP 1 2023-May "" "Create a new taxonomic group in the registry"
.SH NAME
put.taxonomic_group \- put.taxonomic_group(name, id, note)
.SH SYNOPSIS
\fIput.taxonomic_group(name, id, note)\fR
.SH OPTIONS
.PP
\fBname\fB \fR\- . 
.PP
.PP
\fBid\fB \fR\- . 
.PP
.PP
\fBnote\fB \fR\- . 
.PP
.SH VALUE
.PP
the unique reference id of the new taxonomic group in the registry.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.put.taxonomic_group at put.R:line 6
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2023
