.TH PUT.GENOME_GROUP 1 2024-Apr "" "put a group of genome entry onto registry"
.SH NAME
put.genome_group \- put.genome_group(grp, genomes)
.SH SYNOPSIS
\fIput.genome_group(grp, genomes)\fR
.SH OPTIONS
.PP
\fBgrp\fB \fR\- . the taxonomic_group id
.PP
.PP
\fBgenomes\fB \fR\- . a set of genome entry info, a list set of tuple data list in format of ``list(id, name)``.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.put.genome_group at put.R:line 27
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2024
