.TH PUT.GO_TERM 1 2024-Apr "" "put.go_term"
.SH NAME
put.go_term \- put.go_term(term)
.SH SYNOPSIS
\fIput.go_term(term)\fR
.SH OPTIONS
.PP
\fBterm\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.put.go_term at gene_ontology.R:line 9
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2024
