.TH PUT.NCBI_TAX 1 2023-Jun "" "put.ncbi_tax"
.SH NAME
put.ncbi_tax \- put.ncbi_tax(tax)
.SH SYNOPSIS
\fIput.ncbi_tax(tax)\fR
.SH OPTIONS
.PP
\fBtax\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.put.ncbi_tax at ncbi_taxonomy.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2023
