.TH PUT.OPERON 1 2024-Apr "" "put.operon"
.SH NAME
put.operon \- put.operon(genome.id, genes)
.SH SYNOPSIS
\fIput.operon(genome.id, genes)\fR
.SH OPTIONS
.PP
\fBgenome.id\fB \fR\- . 
.PP
.PP
\fBgenes\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.put.operon at put.R:line 38
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2024
