.TH PUT.SEQUENCE 1 2023-Jun "" "put.sequence"
.SH NAME
put.sequence \- put.sequence(gene.id, locus.tag, gene.seq, prot.seq,
    <i>note</i> = <span style='color: blue;'>NULL</span>)
.SH SYNOPSIS
\fIput.sequence(gene.id, locus.tag, gene.seq, prot.seq,
    <i>note</i> = <span style='color: blue;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBgene.id\fB \fR\- . 
.PP
.PP
\fBlocus.tag\fB \fR\- . 
.PP
.PP
\fBgene.seq\fB \fR\- . 
.PP
.PP
\fBprot.seq\fB \fR\- . 
.PP
.PP
\fBnote\fB \fR\- NULL. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.put.sequence at put.R:line 64
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2023
