.TH QUERY_REFSEQ 1 2026-4月 "" "query_refseq"
.SH NAME
query_refseq \- query_refseq(registry, taxname)
.SH SYNOPSIS
\fIquery_refseq(registry, taxname)\fR
.SH OPTIONS
.PP
\fBregistry\fB \fR\- . 
.PP
.PP
\fBtaxname\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.query_refseq at refseq.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2026
