.TH REACTION_MODEL 1 2024-Dec "" "reaction_model"
.SH NAME
reaction_model \- reaction_model(biocad.registry)
.SH SYNOPSIS
\fIreaction_model(biocad.registry)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.reaction_model at biocad_registry.R:line 33
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2024
