.TH RNA_TERM 1 2024-Aug "" "get vocabulary term id of ``RNA``"
.SH NAME
rna_term \- rna_term(biocad.registry)
.SH SYNOPSIS
\fIrna_term(biocad.registry)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.rna_term at biocad_registry.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2024
