.TH SAVE_NUCLEOTIDE_EMBEDDING 1 2025-May "" "save_nucleotide_embedding"
.SH NAME
save_nucleotide_embedding \- save_nucleotide_embedding(biocad.registry, mol.id, dnaseq, sgt, Nucleotide.graph)
.SH SYNOPSIS
\fIsave_nucleotide_embedding(biocad.registry, mol.id, dnaseq, sgt, Nucleotide.graph)\fR
.SH OPTIONS
.PP
\fBbiocad.registry\fB \fR\- . 
.PP
.PP
\fBmol.id\fB \fR\- . 
.PP
.PP
\fBdnaseq\fB \fR\- . 
.PP
.PP
\fBsgt\fB \fR\- . 
.PP
.PP
\fBNucleotide.graph\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.save_nucleotide_embedding at genbank.R:line 89
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
