.TH WRAP_LIST 1 2024-Aug "" "wrap_list"
.SH NAME
wrap_list \- wrap_list(a)
.SH SYNOPSIS
\fIwrap_list(a)\fR
.SH OPTIONS
.PP
\fBa\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.wrap_list at utils.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2024
