Imports Oracle.LinuxCompatibility.MySQL
Imports Oracle.LinuxCompatibility.MySQL.MySqlBuilder
Imports Oracle.LinuxCompatibility.MySQL.Uri

Namespace biocad_registryModel

Public MustInherit Class db_mysql : Inherits IDatabase
Protected ReadOnly m_cluster_link As TableModel(Of cluster_link)
Protected ReadOnly m_complex As TableModel(Of complex)
Protected ReadOnly m_conserved_cluster As TableModel(Of conserved_cluster)
Protected ReadOnly m_db_xrefs As TableModel(Of db_xrefs)
Protected ReadOnly m_genomics As TableModel(Of genomics)
Protected ReadOnly m_hashcode As TableModel(Of hashcode)
Protected ReadOnly m_kinetic_law As TableModel(Of kinetic_law)
Protected ReadOnly m_kinetic_substrate As TableModel(Of kinetic_substrate)
Protected ReadOnly m_mesh As TableModel(Of mesh)
Protected ReadOnly m_mesh_link As TableModel(Of mesh_link)
Protected ReadOnly m_molecule As TableModel(Of molecule)
Protected ReadOnly m_molecule_function As TableModel(Of molecule_function)
Protected ReadOnly m_molecule_ontology As TableModel(Of molecule_ontology)
Protected ReadOnly m_molecule_tags As TableModel(Of molecule_tags)
Protected ReadOnly m_motif As TableModel(Of motif)
Protected ReadOnly m_ncbi_taxonomy As TableModel(Of ncbi_taxonomy)
Protected ReadOnly m_odor As TableModel(Of odor)
Protected ReadOnly m_ontology As TableModel(Of ontology)
Protected ReadOnly m_ontology_tree As TableModel(Of ontology_tree)
Protected ReadOnly m_pathway As TableModel(Of pathway)
Protected ReadOnly m_pathway_graph As TableModel(Of pathway_graph)
Protected ReadOnly m_pubmed As TableModel(Of pubmed)
Protected ReadOnly m_pubmed_source As TableModel(Of pubmed_source)
Protected ReadOnly m_reaction As TableModel(Of reaction)
Protected ReadOnly m_reaction_graph As TableModel(Of reaction_graph)
Protected ReadOnly m_regulation_graph As TableModel(Of regulation_graph)
Protected ReadOnly m_sequence_graph As TableModel(Of sequence_graph)
Protected ReadOnly m_subcellular_compartments As TableModel(Of subcellular_compartments)
Protected ReadOnly m_subcellular_location As TableModel(Of subcellular_location)
Protected ReadOnly m_synonym As TableModel(Of synonym)
Protected ReadOnly m_taxonomy_source As TableModel(Of taxonomy_source)
Protected ReadOnly m_taxonomy_tree As TableModel(Of taxonomy_tree)
Protected ReadOnly m_vocabulary As TableModel(Of vocabulary)
Protected Sub New(mysqli As ConnectionUri)
Call MyBase.New(mysqli)

Me.m_cluster_link = model(Of cluster_link)()
Me.m_complex = model(Of complex)()
Me.m_conserved_cluster = model(Of conserved_cluster)()
Me.m_db_xrefs = model(Of db_xrefs)()
Me.m_genomics = model(Of genomics)()
Me.m_hashcode = model(Of hashcode)()
Me.m_kinetic_law = model(Of kinetic_law)()
Me.m_kinetic_substrate = model(Of kinetic_substrate)()
Me.m_mesh = model(Of mesh)()
Me.m_mesh_link = model(Of mesh_link)()
Me.m_molecule = model(Of molecule)()
Me.m_molecule_function = model(Of molecule_function)()
Me.m_molecule_ontology = model(Of molecule_ontology)()
Me.m_molecule_tags = model(Of molecule_tags)()
Me.m_motif = model(Of motif)()
Me.m_ncbi_taxonomy = model(Of ncbi_taxonomy)()
Me.m_odor = model(Of odor)()
Me.m_ontology = model(Of ontology)()
Me.m_ontology_tree = model(Of ontology_tree)()
Me.m_pathway = model(Of pathway)()
Me.m_pathway_graph = model(Of pathway_graph)()
Me.m_pubmed = model(Of pubmed)()
Me.m_pubmed_source = model(Of pubmed_source)()
Me.m_reaction = model(Of reaction)()
Me.m_reaction_graph = model(Of reaction_graph)()
Me.m_regulation_graph = model(Of regulation_graph)()
Me.m_sequence_graph = model(Of sequence_graph)()
Me.m_subcellular_compartments = model(Of subcellular_compartments)()
Me.m_subcellular_location = model(Of subcellular_location)()
Me.m_synonym = model(Of synonym)()
Me.m_taxonomy_source = model(Of taxonomy_source)()
Me.m_taxonomy_tree = model(Of taxonomy_tree)()
Me.m_vocabulary = model(Of vocabulary)()
End Sub
End Class

End Namespace
