.\" man page create by R# package system.
.TH SETUP 1 2000-Jan "setup_ko" "setup_ko"
.SH NAME
setup_ko \- use KEGG orthology as protein reference model
.SH SYNOPSIS
\fIsetup_ko(\fBregistry\fR as <generic> biocad_registry, 
\fBko\fR as any = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
use KEGG orthology as protein reference model
.PP
.SH OPTIONS
.PP
\fBregistry\fB \fR\- -. 
.PP
.PP
\fBko\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
setup
.SH FILES
.PP
biocad_registry.dll
.PP
