.\" man page create by R# package system.
.TH SETUP 1 2000-Jan "setup_refmet" "setup_refmet"
.SH NAME
setup_refmet \- use kegg+refmet as template for make setup of the metabolites table
.SH SYNOPSIS
\fIsetup_refmet(\fBregistry\fR as <generic> biocad_registry, 
\fBrefmet\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
use kegg+refmet as template for make setup of the metabolites table
.PP
.SH OPTIONS
.PP
\fBrefmet\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
setup
.SH FILES
.PP
biocad_registry.dll
.PP
