.\" man page create by R# package system.
.TH SETUP 1 2000-Jan "setup_lipidmaps" "setup_lipidmaps"
.SH NAME
setup_lipidmaps \- 
.SH SYNOPSIS
\fIsetup_lipidmaps(\fBregistry\fR as <generic> biocad_registry, 
\fBlipidmaps\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
setup
.SH FILES
.PP
biocad_registry.dll
.PP
