.\" man page create by R# package system.
.TH SETUP 1 2000-Jan "setup_metabolites" "setup_metabolites"
.SH NAME
setup_metabolites \- 
.SH SYNOPSIS
\fIsetup_metabolites(\fBregistry\fR as <generic> biocad_registry, 
\fBkegg\fR as any, 
\fBrefmet\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
setup
.SH FILES
.PP
biocad_registry.dll
.PP
