.\" man page create by R# package system.
.TH SETUP 1 2000-Jan "setup_taxonomy" "setup_taxonomy"
.SH NAME
setup_taxonomy \- 
.SH SYNOPSIS
\fIsetup_taxonomy(\fBregistry\fR as <generic> biocad_registry, 
\fBncbi_tax\fR as <generic> NcbiTaxonomyTree);\fR
.SH SEE ALSO
setup
.SH FILES
.PP
biocad_registry.dll
.PP
