.\" man page create by R# package system.
.TH EXPORTS 1 2000-Jan "export_smiles_data" "export_smiles_data"
.SH NAME
export_smiles_data \- 
.SH SYNOPSIS
\fIexport_smiles_data(\fBregistry\fR as <generic> biocad_registry, 
\fBdbname\fR as string);\fR
.SH SEE ALSO
exports
.SH FILES
.PP
biocad_registry.dll
.PP
