.\" man page create by R# package system.
.TH EXPORTS 1 2000-Jan "metabolite_table" "metabolite_table"
.SH NAME
metabolite_table \- 
.SH SYNOPSIS
\fImetabolite_table(\fBregistry\fR as <generic> biocad_registry, 
\fBdbname\fR as string = \fB<NULL>\fR);\fR
.SH SEE ALSO
exports
.SH FILES
.PP
biocad_registry.dll
.PP
