.\" man page create by R# package system.
.TH EXPORTS 1 2000-1月 "virtualcell_componentdb" "virtualcell_componentdb"
.SH NAME
virtualcell_componentdb \- Make exports of the component models for run virtual cell annotations
.SH SYNOPSIS
\fIvirtualcell_componentdb(\fBregistry\fR as <generic> biocad_registry, 
\fBrepo\fR as string, 
\fBtfbs\fR as boolean = TRUE, 
\fBtf\fR as boolean = TRUE, 
\fBcc\fR as boolean = TRUE, 
\fBec\fR as boolean = TRUE, 
\fBrxn\fR as boolean = TRUE, 
\fBmetab\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
Make exports of the component models for run virtual cell annotations
.PP
.SH OPTIONS
.PP
\fBregistry\fB \fR\- -. 
.PP
.PP
\fBrepo\fB \fR\- -. 
.PP
.SH SEE ALSO
exports
.SH FILES
.PP
biocad_registry.dll
.PP
