.\" man page create by R# package system.
.TH EXPORTS 1 2000-Jan "virtualcell_componentdb" "virtualcell_componentdb"
.SH NAME
virtualcell_componentdb \- 
.SH SYNOPSIS
\fIvirtualcell_componentdb(\fBregistry\fR as <generic> biocad_registry, 
\fBrepo\fR as string);\fR
.SH SEE ALSO
exports
.SH FILES
.PP
biocad_registry.dll
.PP
