.\" man page create by R# package system.
.TH DATA_IMPORTS 1 2000-Jan "imports_genomics" "imports_genomics"
.SH NAME
imports_genomics \- 
.SH SYNOPSIS
\fIimports_genomics(\fBregistry\fR as <generic> biocad_registry, 
\fBgenbank\fR as <generic> GenBankScanner);\fR
.SH SEE ALSO
data_imports
.SH FILES
.PP
biocad_registry.dll
.PP
