.\" man page create by R# package system.
.TH DATA_IMPORTS 1 2000-Jan "imports_operon" "imports_operon"
.SH NAME
imports_operon \- 
.SH SYNOPSIS
\fIimports_operon(\fBregistry\fR as <generic> biocad_registry, 
\fBoperon\fR as <generic> OperonRow[]);\fR
.SH SEE ALSO
data_imports
.SH FILES
.PP
biocad_registry.dll
.PP
