.\" man page create by R# package system.
.TH DATA_IMPORTS 1 2000-Jan "imports_dna_seqs" "imports_dna_seqs"
.SH NAME
imports_dna_seqs \- 
.SH SYNOPSIS
\fIimports_dna_seqs(\fBregistry\fR as <generic> biocad_registry, 
\fBgenbank\fR as <generic> GenBankScanner);\fR
.SH SEE ALSO
data_imports
.SH FILES
.PP
biocad_registry.dll
.PP
