.\" man page create by R# package system.
.TH DATA_IMPORTS 1 2000-Jan "imports_chebi_repo" "imports_chebi_repo"
.SH NAME
imports_chebi_repo \- 
.SH SYNOPSIS
\fIimports_chebi_repo(\fBregistry\fR as <generic> biocad_registry, 
\fBchebi\fR as <generic> OBOFile);\fR
.SH SEE ALSO
data_imports
.SH FILES
.PP
biocad_registry.dll
.PP
