.\" man page create by R# package system.
.TH DATA_IMPORTS 1 2000-Jan "imports_taxonomy" "imports_taxonomy"
.SH NAME
imports_taxonomy \- 
.SH SYNOPSIS
\fIimports_taxonomy(\fBregistry\fR as <generic> biocad_registry, 
\fBtaxdump\fR as <generic> NcbiTaxonomyTree);\fR
.SH SEE ALSO
data_imports
.SH FILES
.PP
biocad_registry.dll
.PP
