.\" man page create by R# package system.
.TH DATA_IMPORTS 1 2000-Jan "imports_pubchem_pathway" "imports_pubchem_pathway"
.SH NAME
imports_pubchem_pathway \- 
.SH SYNOPSIS
\fIimports_pubchem_pathway(\fBregistry\fR as <generic> biocad_registry, 
\fBpathways\fR as any, 
\fBtopic\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
data_imports
.SH FILES
.PP
biocad_registry.dll
.PP
