.\" man page create by R# package system.
.TH DATA_IMPORTS 1 2000-Jan "imports_pubchem_repo" "imports_pubchem_repo"
.SH NAME
imports_pubchem_repo \- 
.SH SYNOPSIS
\fIimports_pubchem_repo(\fBregistry\fR as <generic> biocad_registry, 
\fBrepo\fR as <generic> PubChemScanner);\fR
.SH SEE ALSO
data_imports
.SH FILES
.PP
biocad_registry.dll
.PP
