.\" man page create by R# package system.
.TH DATA_IMPORTS 1 2000-Jan "imports_pubmed_kb" "imports_pubmed_kb"
.SH NAME
imports_pubmed_kb \- 
.SH SYNOPSIS
\fIimports_pubmed_kb(\fBregistry\fR as <generic> biocad_registry, 
\fBpubmed\fR as any, 
\fBtopic\fR as string, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
data_imports
.SH FILES
.PP
biocad_registry.dll
.PP
