.\" man page create by R# package system.
.TH DATA_IMPORTS 1 2000-Jan "imports_metab_repo" "imports_metab_repo"
.SH NAME
imports_metab_repo \- 
.SH SYNOPSIS
\fIimports_metab_repo(\fBregistry\fR as <generic> biocad_registry, 
\fBmetab\fR as any, 
\fBlazy_molecule_ctor\fR as boolean = FALSE, 
\fBtopic\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
data_imports
.SH FILES
.PP
biocad_registry.dll
.PP
