.\" man page create by R# package system.
.TH DATA_IMPORTS 1 2000-Jan "imports_dbxrefs" "imports_dbxrefs"
.SH NAME
imports_dbxrefs \- 
.SH SYNOPSIS
\fIimports_dbxrefs(\fBregistry\fR as <generic> biocad_registry, 
\fBgenbank\fR as <generic> GenBankScanner);\fR
.SH SEE ALSO
data_imports
.SH FILES
.PP
biocad_registry.dll
.PP
