.\" man page create by R# package system.
.TH DATA_IMPORTS 1 2000-Jan "imports_uniprot" "imports_uniprot"
.SH NAME
imports_uniprot \- 
.SH SYNOPSIS
\fIimports_uniprot(\fBregistry\fR as <generic> biocad_registry, 
\fBuniprot\fR as string);\fR
.SH SEE ALSO
data_imports
.SH FILES
.PP
biocad_registry.dll
.PP
