.\" man page create by R# package system.
.TH DATA_IMPORTS 1 2000-Jan "imports_lotus_np" "imports_lotus_np"
.SH NAME
imports_lotus_np \- 
.SH SYNOPSIS
\fIimports_lotus_np(\fBregistry\fR as <generic> biocad_registry, 
\fBlotus\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
data_imports
.SH FILES
.PP
biocad_registry.dll
.PP
