.\" man page create by R# package system.
.TH DATA_IMPORTS 1 2000-Jan "imports_genbank_proteins" "imports_genbank_proteins"
.SH NAME
imports_genbank_proteins \- 
.SH SYNOPSIS
\fIimports_genbank_proteins(\fBregistry\fR as <generic> biocad_registry, 
\fBgenbank\fR as <generic> GenBankScanner);\fR
.SH SEE ALSO
data_imports
.SH FILES
.PP
biocad_registry.dll
.PP
