.\" man page create by R# package system.
.TH MODELS 1 2000-1月 "diamond_transaction" "diamond_transaction"
.SH NAME
diamond_transaction \- 
.SH SYNOPSIS
\fIdiamond_transaction(\fBblastp\fR as any, 
\fBdir\fR as string, 
\fBbatch_size\fR as integer = 10000000, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
models
.SH FILES
.PP
biocad_registry.dll
.PP
