.\" man page create by R# package system.
.TH MODELS 1 2000-1月 "imports_interprodb" "imports_interprodb"
.SH NAME
imports_interprodb \- 
.SH SYNOPSIS
\fIimports_interprodb(\fBregistry\fR as <generic> biocad_registry, 
\fBinterpro\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
models
.SH FILES
.PP
biocad_registry.dll
.PP
