.\" man page create by R# package system.
.TH MODELS 1 2000-1月 "imports_diamond" "imports_diamond"
.SH NAME
imports_diamond \- 
.SH SYNOPSIS
\fIimports_diamond(\fBregistry\fR as <generic> biocad_registry, 
\fBblastp\fR as any, 
\fBcheck_unique\fR as boolean = FALSE, 
\fBbatch_size\fR as integer = 500000, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
models
.SH FILES
.PP
biocad_registry.dll
.PP
