.\" man page create by R# package system.
.TH MODELS 1 2000-1月 "imports_pathways" "imports_pathways"
.SH NAME
imports_pathways \- 
.SH SYNOPSIS
\fIimports_pathways(\fBregistry\fR as <generic> biocad_registry, 
\fBpathways\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
models
.SH FILES
.PP
biocad_registry.dll
.PP
