.\" man page create by R# package system.
.TH MODELS 1 2000-1月 "make_protein_clusters" "make_protein_clusters"
.SH NAME
make_protein_clusters \- 
.SH SYNOPSIS
\fImake_protein_clusters(\fBregistry\fR as <generic> biocad_registry, 
\fBcutoff\fR as double = 30, 
\fBeval_cutoff\fR as double = 1E-05);\fR
.SH SEE ALSO
models
.SH FILES
.PP
biocad_registry.dll
.PP
