.\" man page create by R# package system.
.TH MODELS 1 2000-Jan "register_metabolic_symbols" "register_metabolic_symbols"
.SH NAME
register_metabolic_symbols \- 
.SH SYNOPSIS
\fIregister_metabolic_symbols(\fBregistry\fR as <generic> biocad_registry);\fR
.SH SEE ALSO
models
.SH FILES
.PP
biocad_registry.dll
.PP
