.\" man page create by R# package system.
.TH MODELS 1 2000-Jan "update_location" "update_location"
.SH NAME
update_location \- make updates of the compartment location metadata
.SH SYNOPSIS
\fIupdate_location(\fBregistry\fR as <generic> biocad_registry, 
\fBlocations\fR as <generic> dataframe);\fR
.SH DESCRIPTION
.PP
make updates of the compartment location metadata
.PP
.SH OPTIONS
.PP
\fBregistry\fB \fR\- -. 
.PP
.PP
\fBlocations\fB \fR\- -. 
.PP
.SH SEE ALSO
models
.SH FILES
.PP
biocad_registry.dll
.PP
