.\" man page create by R# package system.
.TH MODELS 1 2000-Jan "update_location" "update_location"
.SH NAME
update_location \- 
.SH SYNOPSIS
\fIupdate_location(\fBregistry\fR as <generic> biocad_registry, 
\fBlocations\fR as <generic> dataframe);\fR
.SH SEE ALSO
models
.SH FILES
.PP
biocad_registry.dll
.PP
