require(biocad_registry);

imports "massbank" from "mzkit";
imports "registry" from "biocad_registry";

let biocad_registry = open_registry("xieguigang", 123456, host ="192.168.3.15");
let mona = read.MoNA([
    "J:\MoNA\MoNA-export-Volatile_FiehnLib.msp"
    "J:\MoNA\MoNA-export-Alkaloids_QE_neg.msp"
    "J:\MoNA\MoNA-export-Alkaloids_QE_pos.msp"
    "J:\MoNA\MoNA-export-All_LC-MS-MS_Agilent_QTOF.msp"
    "J:\MoNA\MoNA-export-All_LC-MS-MS_Orbitrap.msp"
    "J:\MoNA\MoNA-export-All_LC-MS-MS_QTOF.msp"
    "J:\MoNA\MoNA-export-CASMI_2012.msp"
    "J:\MoNA\MoNA-export-CASMI_2016.msp"
    "J:\MoNA\MoNA-export-CD_annotated_EnvCpd_suspect_metabolites_NCU_HILIC_NEG.msp"
    "J:\MoNA\MoNA-export-CD_annotated_EnvCpd_suspect_metabolites_NCU_HILIC_POS.msp"
    "J:\MoNA\MoNA-export-CD_annotated_EnvCpd_suspect_metabolites_NCU_RP_NEG.msp"
    "J:\MoNA\MoNA-export-CD_annotated_EnvCpd_suspect_metabolites_NCU_RP_POS.msp"
    "J:\MoNA\MoNA-export-Dipeptide_neg.msp"
    "J:\MoNA\MoNA-export-Dipeptide_pos.msp"
    "J:\MoNA\MoNA-export-DNAAdduct.msp"
    "J:\MoNA\MoNA-export-EMBL-MCF.msp"
    "J:\MoNA\MoNA-export-EMBL-MCF_2.0_HRMS_Library.msp"
    "J:\MoNA\MoNA-export-FAHFA.msp"
    "J:\MoNA\MoNA-export-Fiehn_HILIC.msp"
    "J:\MoNA\MoNA-export-Fungicide_NCU.msp"
    "J:\MoNA\MoNA-export-Fungicide_NCU_HIL_POS.msp"
    "J:\MoNA\MoNA-export-Fungicide_NCU_RP_NEG.msp"
    "J:\MoNA\MoNA-export-Fungicide_NCU_RP_POS.msp"
    "J:\MoNA\MoNA-export-Fungicide_suspect_metabolites_NCU_HIL_NEG.msp"
    "J:\MoNA\MoNA-export-Fungicide_suspect_metabolites_NCU_HIL_POS.msp"
    "J:\MoNA\MoNA-export-Fungicide_suspect_metabolites_NCU_RP_NEG.msp"
    "J:\MoNA\MoNA-export-Fungicide_suspect_metabolites_NCU_RP_POS.msp"
    "J:\MoNA\MoNA-export-GNPS.msp"
    "J:\MoNA\MoNA-export-HCD_natural_product_library.msp"
    "J:\MoNA\MoNA-export-HMDB.msp"
    "J:\MoNA\MoNA-export-Human_Plasma_Quant.msp"
    "J:\MoNA\MoNA-export-IstdOrbitrapHILICNeg.msp"
    "J:\MoNA\MoNA-export-IstdOrbitrapHILICPos.msp"
    "J:\MoNA\MoNA-export-IstdTToFHILICPos.msp"
    "J:\MoNA\MoNA-export-LC-MS-MS_Negative_Mode.msp"
    "J:\MoNA\MoNA-export-LC-MS-MS_Positive_Mode.msp"
    "J:\MoNA\MoNA-export-LipidBlast.msp"
    "J:\MoNA\MoNA-export-LipidBlast_2022.msp"
    "J:\MoNA\MoNA-export-MassBank.msp"
    "J:\MoNA\MoNA-export-MetaboBASE.msp"
    "J:\MoNA\MoNA-export-MetaSci.msp"
    "J:\MoNA\MoNA-export-Nutrimetabolomics@FEM.msp"
    "J:\MoNA\MoNA-export-Pathogen_Box.msp"
    "J:\MoNA\MoNA-export-PFP_NP_library.msp"
    "J:\MoNA\MoNA-export-Polyphenol_neg.msp"
    "J:\MoNA\MoNA-export-POS_Metabolite_IDX.msp"
    "J:\MoNA\MoNA-export-QiaoLab_PGN.msp"
    "J:\MoNA\MoNA-export-ReSpect.msp"
    "J:\MoNA\MoNA-export-RIKEN_IMS_Oxidized_Phospholipids.msp"
    "J:\MoNA\MoNA-export-RTX5_Fiehnlib.msp"
    "J:\MoNA\MoNA-export-TOF_alkaloids_neg.msp"
    "J:\MoNA\MoNA-export-TOF_alkaloids_pos.msp"
    "J:\MoNA\MoNA-export-Vaniya-Fiehn_Natural_Products_Library.msp"
], lazy = FALSE);

biocad_registry |> imports_mona(mona);