-- MySQL Script generated by MySQL Workbench
-- Sun Jan 11 21:53:16 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cad_registry
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cad_registry` ;

-- -----------------------------------------------------
-- Schema cad_registry
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cad_registry` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `cad_registry` ;

-- -----------------------------------------------------
-- Table `cad_registry`.`compartment_enrich`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`compartment_enrich` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`compartment_enrich` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `metabolite_id` INT UNSIGNED NOT NULL,
  `location_id` INT UNSIGNED NOT NULL,
  `evidence` VARCHAR(1024) NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `metabolite_data`
    FOREIGN KEY (`metabolite_id`)
    REFERENCES `cad_registry`.`metabolites` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `location_data`
    FOREIGN KEY (`location_id`)
    REFERENCES `cad_registry`.`compartment_location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'metabolite ~ compartment location association';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`compartment_enrich` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `metabolite_data_idx` ON `cad_registry`.`compartment_enrich` (`metabolite_id` ASC) INVISIBLE;

SHOW WARNINGS;
CREATE INDEX `location_data_idx` ON `cad_registry`.`compartment_enrich` (`location_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `unique_link` ON `cad_registry`.`compartment_enrich` (`metabolite_id` ASC, `location_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`compartment_location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`compartment_location` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`compartment_location` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT 'symbol name that used in virtual cell model',
  `fullname` VARCHAR(1024) NOT NULL COMMENT 'full name of this location',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` MEDIUMTEXT NULL COMMENT 'description note about this cellular location',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '[cellular entity model] cellular location name';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`compartment_location` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `name_UNIQUE` ON `cad_registry`.`compartment_location` (`name` ASC) VISIBLE;

SHOW WARNINGS;
CREATE FULLTEXT INDEX `search_text` ON `cad_registry`.`compartment_location` (`fullname`, `note`) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`complex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`complex` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`complex` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `protein_id` INT UNSIGNED NOT NULL COMMENT 'id of the protein complex entity which is defined inside protein',
  `compound_id` INT UNSIGNED NOT NULL COMMENT 'the one of the compound of this protein complex entity, compound could be metabolite, gene(rna) and another protein ',
  `compound_type` INT UNSIGNED NOT NULL COMMENT 'the entity type of this compound object',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `metabolite_compound`
    FOREIGN KEY (`compound_id`)
    REFERENCES `cad_registry`.`metabolites` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rna_compound`
    FOREIGN KEY (`compound_id`)
    REFERENCES `cad_registry`.`gene` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `protein_compound`
    FOREIGN KEY (`compound_id`)
    REFERENCES `cad_registry`.`protein` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `protein_complex`
    FOREIGN KEY (`protein_id`)
    REFERENCES `cad_registry`.`protein` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `entity_namespace`
    FOREIGN KEY (`compound_type`)
    REFERENCES `cad_registry`.`vocabulary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'components for used for protein complex';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`complex` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `metabolite_compound_idx` ON `cad_registry`.`complex` (`compound_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `protein_complex_idx` ON `cad_registry`.`complex` (`protein_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `entity_namespace_idx` ON `cad_registry`.`complex` (`compound_type` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `unique_compound` ON `cad_registry`.`complex` (`protein_id` ASC, `compound_id` ASC, `compound_type` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`conserved_operon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`conserved_operon` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`conserved_operon` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL COMMENT 'the conserved operon name',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'conserved gene operon cluster across multiple species';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`conserved_operon` (`id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`db_xrefs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`db_xrefs` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`db_xrefs` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `obj_id` INT UNSIGNED NOT NULL COMMENT 'object reference id to the metabolites/genes/protein/compartment location/reaction table',
  `type` INT UNSIGNED NOT NULL COMMENT 'entity type of the object that associated with this database corss reference id',
  `db_name` INT UNSIGNED NOT NULL COMMENT 'database name of the db_xref id',
  `db_xref` VARCHAR(500) NOT NULL COMMENT 'database cross reference id',
  `db_source` INT UNSIGNED NOT NULL COMMENT 'source trace of this relation ship where it comes from',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  CONSTRAINT `source_name`
    FOREIGN KEY (`db_source`)
    REFERENCES `cad_registry`.`vocabulary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `entity_namespace`
    FOREIGN KEY (`type`)
    REFERENCES `cad_registry`.`vocabulary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `dbname`
    FOREIGN KEY (`db_name`)
    REFERENCES `cad_registry`.`vocabulary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `entity_metabolite`
    FOREIGN KEY (`obj_id`)
    REFERENCES `cad_registry`.`metabolites` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `entity_gene`
    FOREIGN KEY (`obj_id`)
    REFERENCES `cad_registry`.`gene` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `entity_protein`
    FOREIGN KEY (`obj_id`)
    REFERENCES `cad_registry`.`protein` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `entity_reaction`
    FOREIGN KEY (`obj_id`)
    REFERENCES `cad_registry`.`reaction` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `entity_location`
    FOREIGN KEY (`obj_id`)
    REFERENCES `cad_registry`.`compartment_location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'database cross reference of the model objects ';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`db_xrefs` (`id` ASC) INVISIBLE;

SHOW WARNINGS;
CREATE INDEX `source_name_idx` ON `cad_registry`.`db_xrefs` (`db_source` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `entity_namespace_idx` ON `cad_registry`.`db_xrefs` (`type` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `dbname_idx` ON `cad_registry`.`db_xrefs` (`db_name` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `entity_metabolite_idx` ON `cad_registry`.`db_xrefs` (`obj_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `find_by_xref` ON `cad_registry`.`db_xrefs` (`db_name` ASC, `db_xref` ASC, `type` ASC) INVISIBLE;

SHOW WARNINGS;
CREATE INDEX `find_by_object` ON `cad_registry`.`db_xrefs` (`type` ASC, `obj_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `unique_xref` ON `cad_registry`.`db_xrefs` (`obj_id` ASC, `type` ASC, `db_name` ASC, `db_xref` ASC, `db_source` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`gene`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`gene` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`gene` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL COMMENT 'gene name',
  `function` MEDIUMTEXT NULL COMMENT 'gene product function description text',
  `gene_cluster` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'id reference to the conserved operon table, to indicates that this gene model is belongs to which conserved gene clusters. default zero means this gene not belongs to any cluster',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `cluster_info`
    FOREIGN KEY (`gene_cluster`)
    REFERENCES `cad_registry`.`conserved_operon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '[cellular entity model] a table of the reference gene model, just defined the gene object at here';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`gene` (`id` ASC) INVISIBLE;

SHOW WARNINGS;
CREATE INDEX `cluster_info_idx` ON `cad_registry`.`gene` (`gene_cluster` ASC) VISIBLE;

SHOW WARNINGS;
CREATE FULLTEXT INDEX `search_text` ON `cad_registry`.`gene` (`function`, `note`) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `name_hit` ON `cad_registry`.`gene` (`name` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`gene_ontology`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`gene_ontology` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`gene_ontology` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `gene_id` INT UNSIGNED NOT NULL,
  `ontology_id` INT UNSIGNED NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `gene_data`
    FOREIGN KEY (`gene_id`)
    REFERENCES `cad_registry`.`nucleotide_data` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ontology_term`
    FOREIGN KEY (`ontology_id`)
    REFERENCES `cad_registry`.`ontology` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`gene_ontology` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `ontology_term_idx` ON `cad_registry`.`gene_ontology` (`ontology_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `gene_data_idx` ON `cad_registry`.`gene_ontology` (`gene_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `unique_feature` ON `cad_registry`.`gene_ontology` (`gene_id` ASC, `ontology_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`kinetics_law`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`kinetics_law` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`kinetics_law` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ec_number` VARCHAR(16) NOT NULL COMMENT 'ec number of this kinetics law(or enzyme protein)',
  `enzyme_id` INT UNSIGNED NOT NULL COMMENT 'id reference to the protein model table',
  `lambda` VARCHAR(4096) NOT NULL COMMENT 'the math expression for this kinetics law, usually be the Michaelis-Menten equation: v = vmax * S / (km + S)',
  `parameters` JSON NOT NULL COMMENT 'parameter values for the lambda expression, a key-value pair tuple json data, store the kinetics constant at here, example as there is a kinetics lambda expression: v = vmax * S / (km + S), parameter value json could be {vmax: 1000, S: registry_resolver_id, km: 500}, where number in parameter value is a constant value that detected from the experiment and S is the substrate, value is the model registry resolver id, could be unify mapping to metabolite or other biomolecule entity object',
  `metabolic_node` INT UNSIGNED NOT NULL COMMENT 'metabolic network id, mount this enzyme kinetics law model to a metabolic reaction',
  `buffer` VARCHAR(4096) NULL COMMENT 'experiment condition description',
  `ph` DOUBLE NOT NULL COMMENT 'experiment ph value',
  `temperature` DOUBLE NOT NULL COMMENT 'experiment temperature value',
  `pdb_data` INT UNSIGNED NOT NULL COMMENT 'structure data of this kinetics law: molecule docking visual of the enzyme with the substrate molecule',
  `add_time` DATETIME NOT NULL,
  `note` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `enzyme_protein`
    FOREIGN KEY (`enzyme_id`)
    REFERENCES `cad_registry`.`protein` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `metabolic_netnode`
    FOREIGN KEY (`metabolic_node`)
    REFERENCES `cad_registry`.`metabolic_network` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `docking_result`
    FOREIGN KEY (`pdb_data`)
    REFERENCES `cad_registry`.`pdb` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'enzyme kinetics law, the kinetics law has a unify unit at here, all kinetics law in this table its parameter value must be converted to the standard unit before it save into this table: standard unit of time is second(s), velocity standard unit is mmol/L/s, Km standard unit is (mM)';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`kinetics_law` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `enzyme_protein_idx` ON `cad_registry`.`kinetics_law` (`enzyme_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `metabolic_netnode_idx` ON `cad_registry`.`kinetics_law` (`metabolic_node` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `docking_result_idx` ON `cad_registry`.`kinetics_law` (`pdb_data` ASC) VISIBLE;

SHOW WARNINGS;
CREATE FULLTEXT INDEX `search_text` ON `cad_registry`.`kinetics_law` (`buffer`, `note`) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`metabolic_network`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`metabolic_network` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`metabolic_network` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `reaction_id` INT UNSIGNED NOT NULL COMMENT 'reference to the reaction model node',
  `factor` INT UNSIGNED NOT NULL COMMENT 'stoichiometric number',
  `species_id` INT UNSIGNED NOT NULL COMMENT 'molecule entity id, reference to the registry resolver table, unify reference to metabolite id, gene(rna) id, or protein id',
  `symbol_id` VARCHAR(45) NOT NULL COMMENT 'symbol of the species_id',
  `role` INT UNSIGNED NOT NULL COMMENT 'role of this species, vocabulary term reference id, vocabulary term could be substrate, product, enzyme, inhibitor',
  `compartment_id` INT UNSIGNED NOT NULL COMMENT 'compartment location of this species compound',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `reaction_model`
    FOREIGN KEY (`reaction_id`)
    REFERENCES `cad_registry`.`reaction` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `role_term`
    FOREIGN KEY (`role`)
    REFERENCES `cad_registry`.`vocabulary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `location_info`
    FOREIGN KEY (`compartment_id`)
    REFERENCES `cad_registry`.`compartment_location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `registry_model`
    FOREIGN KEY (`species_id`)
    REFERENCES `cad_registry`.`registry_resolver` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'metabolic reaction network';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`metabolic_network` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `reaction_model_idx` ON `cad_registry`.`metabolic_network` (`reaction_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `role_term_idx` ON `cad_registry`.`metabolic_network` (`role` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `location_info_idx` ON `cad_registry`.`metabolic_network` (`compartment_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `registry_model_idx` ON `cad_registry`.`metabolic_network` (`species_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `symbol_index` ON `cad_registry`.`metabolic_network` (`symbol_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`metabolite_class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`metabolite_class` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`metabolite_class` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `metabolite_id` INT UNSIGNED NOT NULL,
  `class_id` INT UNSIGNED NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `metabolite_info`
    FOREIGN KEY (`metabolite_id`)
    REFERENCES `cad_registry`.`metabolites` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `class_info`
    FOREIGN KEY (`class_id`)
    REFERENCES `cad_registry`.`ontology` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`metabolite_class` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `metabolite_info_idx` ON `cad_registry`.`metabolite_class` (`metabolite_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `class_info_idx` ON `cad_registry`.`metabolite_class` (`class_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `unique_class` ON `cad_registry`.`metabolite_class` (`metabolite_id` ASC, `class_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`metabolites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`metabolites` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`metabolites` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(2048) NOT NULL,
  `hashcode` CHAR(32) NOT NULL COMMENT 'md5 checksum of the tolower(name)',
  `formula` VARCHAR(128) NOT NULL,
  `exact_mass` DOUBLE UNSIGNED NOT NULL DEFAULT 0,
  `cas_id` VARCHAR(32) NULL COMMENT 'cas registry number',
  `pubchem_cid` INT UNSIGNED NULL COMMENT 'pubchem cid(not sid)',
  `chebi_id` INT UNSIGNED NULL COMMENT 'chebi id',
  `hmdb_id` VARCHAR(16) NULL COMMENT 'hmdb id',
  `lipidmaps_id` VARCHAR(16) NULL COMMENT 'lipidmaps id',
  `kegg_id` VARCHAR(6) NULL COMMENT 'kegg compound id',
  `drugbank_id` VARCHAR(45) NULL,
  `biocyc` VARCHAR(1024) NULL COMMENT 'biocyc database id',
  `mesh_id` VARCHAR(1024) NULL COMMENT 'ncbi pubmed mesh id',
  `wikipedia` VARCHAR(1024) NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` LONGTEXT NULL COMMENT 'the metabolite description text, extract from the pubmed articles or genertaed via LLMs',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '[cellular entity model][entity instance] a set of reference metabolites, template based on the www.metabolomicsworkbench.org refmet dataset';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`metabolites` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE FULLTEXT INDEX `search_text` ON `cad_registry`.`metabolites` (`name`, `note`) INVISIBLE;

SHOW WARNINGS;
CREATE INDEX `find_name` ON `cad_registry`.`metabolites` (`hashcode` ASC) INVISIBLE;

SHOW WARNINGS;
CREATE INDEX `find_formula` ON `cad_registry`.`metabolites` (`formula` ASC) INVISIBLE;

SHOW WARNINGS;
CREATE INDEX `filter_mass` ON `cad_registry`.`metabolites` (`exact_mass` ASC) INVISIBLE;

SHOW WARNINGS;
CREATE INDEX `find_cas_id` ON `cad_registry`.`metabolites` (`cas_id` ASC) INVISIBLE;

SHOW WARNINGS;
CREATE INDEX `find_pubchem` ON `cad_registry`.`metabolites` (`pubchem_cid` ASC) INVISIBLE;

SHOW WARNINGS;
CREATE INDEX `find_chebi` ON `cad_registry`.`metabolites` (`chebi_id` ASC) INVISIBLE;

SHOW WARNINGS;
CREATE INDEX `find_hmdb` ON `cad_registry`.`metabolites` (`hmdb_id` ASC) INVISIBLE;

SHOW WARNINGS;
CREATE INDEX `find_lipidmaps` ON `cad_registry`.`metabolites` (`lipidmaps_id` ASC) INVISIBLE;

SHOW WARNINGS;
CREATE INDEX `find_kegg` ON `cad_registry`.`metabolites` (`kegg_id` ASC) INVISIBLE;

SHOW WARNINGS;
CREATE INDEX `find_biocyc` ON `cad_registry`.`metabolites` (`biocyc` ASC) INVISIBLE;

SHOW WARNINGS;
CREATE INDEX `find_mesh` ON `cad_registry`.`metabolites` (`mesh_id` ASC) INVISIBLE;

SHOW WARNINGS;
CREATE INDEX `find_wiki` ON `cad_registry`.`metabolites` (`wikipedia` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`molecular_networking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`molecular_networking` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`molecular_networking` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `u` INT UNSIGNED NOT NULL COMMENT 'id of the molecule data, reference to the metabolites table, nucleotide table, protein data table based on the value of type field',
  `v` INT UNSIGNED NOT NULL COMMENT 'id of the molecule data, reference to the metabolites table, nucleotide table, protein data table based on the value of type field',
  `similarity` DOUBLE NOT NULL COMMENT 'cosine similarity value between two embedding vector',
  `type` INT UNSIGNED NOT NULL COMMENT 'the molecule type of this network edge, value could be metabolite vs metabolite, gene vs gene, protein vs protein',
  `add_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `metabolite_network`
    FOREIGN KEY (`u` , `v`)
    REFERENCES `cad_registry`.`metabolites` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `protein_network`
    FOREIGN KEY (`u` , `v`)
    REFERENCES `cad_registry`.`protein_data` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `gene_network`
    FOREIGN KEY (`u` , `v`)
    REFERENCES `cad_registry`.`nucleotide_data` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `molecule_type`
    FOREIGN KEY (`type`)
    REFERENCES `cad_registry`.`vocabulary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'networking result based on the biological molecule fingerprint embedding vector similarity networking method';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`molecular_networking` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `metabolite_network_idx` ON `cad_registry`.`molecular_networking` (`u` ASC, `v` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `molecule_type_idx` ON `cad_registry`.`molecular_networking` (`type` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `sort_smilarity` ON `cad_registry`.`molecular_networking` (`type` ASC, `similarity` DESC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`motif`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`motif` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`motif` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL COMMENT 'motif name',
  `family` VARCHAR(45) NOT NULL COMMENT 'motif family name',
  `pwm` LONGTEXT NOT NULL COMMENT 'pre-computed motif pwm matrix, base64 encoded of double[][] matrix, network byte order',
  `width` INT NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`motif` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `family_index` ON `cad_registry`.`motif` (`family` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `name_search` ON `cad_registry`.`motif` (`name` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`ncbi_taxonomy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`ncbi_taxonomy` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`ncbi_taxonomy` (
  `id` INT UNSIGNED NOT NULL COMMENT 'the ncbi taxonomy id',
  `name` VARCHAR(1024) NOT NULL COMMENT 'taxonomy name',
  `zh_name` VARCHAR(255) NULL COMMENT 'chinese name translation of this node name',
  `rank` INT UNSIGNED NOT NULL COMMENT 'rank level of this taxonomy node, rank name is reference to the vocabulary term table',
  `ancestor` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'ancestor taxonomy node id, this value for root node is zero',
  `num_childs` INT NOT NULL DEFAULT 0 COMMENT 'number of the direct child of this taxonomy node it have, leaf node is zero',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `taxonomy_tree`
    FOREIGN KEY (`ancestor`)
    REFERENCES `cad_registry`.`ncbi_taxonomy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rank_name`
    FOREIGN KEY (`rank`)
    REFERENCES `cad_registry`.`vocabulary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '[entity instance] the ncbi taxonomy tree data';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`ncbi_taxonomy` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `taxonomy_tree_idx` ON `cad_registry`.`ncbi_taxonomy` (`ancestor` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `rank_name_idx` ON `cad_registry`.`ncbi_taxonomy` (`rank` ASC) VISIBLE;

SHOW WARNINGS;
CREATE FULLTEXT INDEX `search_text` ON `cad_registry`.`ncbi_taxonomy` (`name`, `note`) INVISIBLE;

SHOW WARNINGS;
CREATE INDEX `find_by_scientific_name` ON `cad_registry`.`ncbi_taxonomy` (`name` ASC) INVISIBLE;

SHOW WARNINGS;
CREATE INDEX `find_by_zh_name` ON `cad_registry`.`ncbi_taxonomy` (`zh_name` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`nucleotide_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`nucleotide_data` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`nucleotide_data` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `source_id` VARCHAR(45) NULL COMMENT 'db_xref id of this nucleotide sequence in its source database, example as ncbi genbank accession id',
  `source_db` INT UNSIGNED NOT NULL COMMENT 'source database name, id reference to vocabulary table',
  `name` VARCHAR(45) NULL COMMENT 'name of this nucleotide object(gene or motif site)',
  `function` VARCHAR(2048) NULL COMMENT 'gene product function description text',
  `is_motif` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'boolean type, 1 for true, means is a motif site, 0 for false, means is a gene object instance, default is zero (gene object)',
  `left` INT UNSIGNED NOT NULL COMMENT 'left location on the chromosome',
  `strand` CHAR(1) NOT NULL DEFAULT '+' COMMENT 'value is +/-, means forward or reversed strand',
  `operon_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'id of the operon instance object, default zero means current nucleotide object not belongs to any operon',
  `model_id` INT UNSIGNED NOT NULL COMMENT 'id reference to the gene model table or motif model table',
  `organism_source` INT UNSIGNED NOT NULL COMMENT 'ncbi taxonomy id',
  `sequence` LONGTEXT NULL COMMENT 'nucleotide sequence in upper case',
  `checksum` CHAR(32) NULL COMMENT 'md5 checksum of the sequence',
  `fingerprint` LONGTEXT NULL COMMENT ' embedding vector of this sequence, base64 encoded double array, network byte order',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  CONSTRAINT `gene_model`
    FOREIGN KEY (`model_id`)
    REFERENCES `cad_registry`.`gene` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `dbname`
    FOREIGN KEY (`source_db`)
    REFERENCES `cad_registry`.`vocabulary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `taxonomy_source`
    FOREIGN KEY (`organism_source`)
    REFERENCES `cad_registry`.`ncbi_taxonomy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `motif_model`
    FOREIGN KEY (`model_id`)
    REFERENCES `cad_registry`.`motif` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `operon_data`
    FOREIGN KEY (`operon_id`)
    REFERENCES `cad_registry`.`operon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '[entity instance] gene object instance, nucleotide sequence region instance, used for build a local blastn database, or TFBS motif database';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`nucleotide_data` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `gene_model_idx` ON `cad_registry`.`nucleotide_data` (`model_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `dbname_idx` ON `cad_registry`.`nucleotide_data` (`source_db` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `taxonomy_source_idx` ON `cad_registry`.`nucleotide_data` (`organism_source` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `operon_data_idx` ON `cad_registry`.`nucleotide_data` (`operon_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`ontology`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`ontology` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`ontology` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `term_id` VARCHAR(128) NOT NULL COMMENT 'ontology term id',
  `term` VARCHAR(2048) NOT NULL COMMENT 'term name',
  `ontology_id` INT UNSIGNED NOT NULL COMMENT 'external ontology database name, example as gene_ontology for gene_data, protein_ontology for protein_data, chebi ontology for metabolites',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` LONGTEXT NULL COMMENT 'term description text',
  PRIMARY KEY (`id`),
  CONSTRAINT `ontology_db`
    FOREIGN KEY (`ontology_id`)
    REFERENCES `cad_registry`.`vocabulary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'ontology terms, classification system';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`ontology` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `ontology_db_idx` ON `cad_registry`.`ontology` (`ontology_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE FULLTEXT INDEX `search_text` ON `cad_registry`.`ontology` (`term`, `note`) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `unique_term` ON `cad_registry`.`ontology` (`term_id` ASC, `ontology_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`ontology_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`ontology_relation` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`ontology_relation` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `term_id` INT UNSIGNED NOT NULL COMMENT 'current ontology term node',
  `is_a` INT UNSIGNED NOT NULL COMMENT 'id reference to its parent node',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `term_node`
    FOREIGN KEY (`term_id`)
    REFERENCES `cad_registry`.`ontology` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `parent_node`
    FOREIGN KEY (`is_a`)
    REFERENCES `cad_registry`.`ontology` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`ontology_relation` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `term_node_idx` ON `cad_registry`.`ontology_relation` (`term_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `parent_node_idx` ON `cad_registry`.`ontology_relation` (`is_a` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `unique_relation` ON `cad_registry`.`ontology_relation` (`term_id` ASC, `is_a` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`operon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`operon` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`operon` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `conserved_operon` INT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `conserved_info`
    FOREIGN KEY (`conserved_operon`)
    REFERENCES `cad_registry`.`conserved_operon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'operon instance objects';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`operon` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `conserved_info_idx` ON `cad_registry`.`operon` (`conserved_operon` ASC) VISIBLE;

SHOW WARNINGS;
CREATE FULLTEXT INDEX `search_text` ON `cad_registry`.`operon` (`name`, `note`) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`organism_source`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`organism_source` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`organism_source` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `metabolite_id` INT UNSIGNED NOT NULL COMMENT 'reference to the metabolite information',
  `organism_id` INT UNSIGNED NOT NULL COMMENT 'organism source its ncbi taxonomy id',
  `evidence` VARCHAR(1024) NOT NULL DEFAULT '-' COMMENT 'usually be the article DOI id/ncbi pubmed id ',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `metabolite_data`
    FOREIGN KEY (`metabolite_id`)
    REFERENCES `cad_registry`.`metabolites` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `organism_info`
    FOREIGN KEY (`organism_id`)
    REFERENCES `cad_registry`.`ncbi_taxonomy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'metabolite organism source report, or the lcms experiment annotation result based on the experiment sample information associated with the organism information ';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`organism_source` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `metabolite_data_idx` ON `cad_registry`.`organism_source` (`metabolite_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `organism_info_idx` ON `cad_registry`.`organism_source` (`organism_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`pathway_network`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`pathway_network` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`pathway_network` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pathway_id` INT UNSIGNED NOT NULL,
  `event_id` INT UNSIGNED NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `pathway_info`
    FOREIGN KEY (`pathway_id`)
    REFERENCES `cad_registry`.`pathway_view` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `biological_events`
    FOREIGN KEY (`event_id`)
    REFERENCES `cad_registry`.`reaction` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`pathway_network` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `pathway_info_idx` ON `cad_registry`.`pathway_network` (`pathway_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `biological_events_idx` ON `cad_registry`.`pathway_network` (`event_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`pathway_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`pathway_view` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`pathway_view` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(1024) NOT NULL COMMENT 'the pathway name',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` LONGTEXT NULL COMMENT 'pathway description text',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'pathway view(a collection of reaction models) and biological event view.';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`pathway_view` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE FULLTEXT INDEX `search_text` ON `cad_registry`.`pathway_view` (`name`, `note`) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`pdb`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`pdb` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`pdb` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pdb_id` VARCHAR(8) NOT NULL DEFAULT 'NA' COMMENT 'the id of this pdb structre data, reference to the pdb database, this field could be NA if this structre data is generated via molecule docking',
  `title` MEDIUMTEXT NULL,
  `data` LONGTEXT NOT NULL COMMENT 'base64 encoded pdb text data',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'molecule 3d structure data, store data in pdb data format';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`pdb` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE FULLTEXT INDEX `search_text` ON `cad_registry`.`pdb` (`title`, `note`) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`protein`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`protein` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`protein` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL COMMENT 'protein name',
  `template` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'reference to the gene model table id that gene object that could be used as the template for produce this protein, default value is zero means this protein is artificial designed or it is a protein complex object',
  `pdb_data` INT UNSIGNED NOT NULL COMMENT 'reference to the table of pdb structure data, avaible for the protein complex object',
  `function` MEDIUMTEXT NULL COMMENT 'protein function description text',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `gene_source`
    FOREIGN KEY (`template`)
    REFERENCES `cad_registry`.`gene` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pdb_data`
    FOREIGN KEY (`pdb_data`)
    REFERENCES `cad_registry`.`pdb` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '[cellular entity model] a table of the reference protein models, just defined the protein model information at here, usually be the KO/COG orthology data model';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`protein` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `gene_source_idx` ON `cad_registry`.`protein` (`template` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `pdb_data_idx` ON `cad_registry`.`protein` (`pdb_data` ASC) VISIBLE;

SHOW WARNINGS;
CREATE FULLTEXT INDEX `search_text` ON `cad_registry`.`protein` (`function`, `note`) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `name_hit` ON `cad_registry`.`protein` (`name` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`protein_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`protein_data` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`protein_data` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `source_id` VARCHAR(45) NOT NULL COMMENT 'id in source database, example as uniprot id',
  `source_db` INT UNSIGNED NOT NULL COMMENT 'vocabulary term id to the source database name',
  `name` VARCHAR(45) NOT NULL COMMENT 'protein name',
  `function` VARCHAR(2048) NOT NULL COMMENT 'the protein function description',
  `gene_id` INT UNSIGNED NOT NULL COMMENT 'reference to the gene instance id(not gene model table)',
  `protein_id` INT UNSIGNED NOT NULL COMMENT 'id reference to the reference protein table(protein model table)',
  `sequence` LONGTEXT NOT NULL COMMENT 'protein sequence, should be in upper case',
  `checksum` CHAR(32) NOT NULL COMMENT 'md5 hash checksum of the protein sequence',
  `fingerprint` LONGTEXT NULL COMMENT ' embedding vector of this sequence, base64 encoded double array, network byte order',
  `pdb_data` INT UNSIGNED NOT NULL COMMENT 'reference to the pdb table, used for the web visualization of this protein object',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  CONSTRAINT `translate_from`
    FOREIGN KEY (`gene_id`)
    REFERENCES `cad_registry`.`nucleotide_data` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `protein_model`
    FOREIGN KEY (`protein_id`)
    REFERENCES `cad_registry`.`protein` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `dbname`
    FOREIGN KEY (`source_db`)
    REFERENCES `cad_registry`.`vocabulary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pdb_datavalue`
    FOREIGN KEY (`pdb_data`)
    REFERENCES `cad_registry`.`pdb` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '[entity instance] the instance of the protein with sequence data, used for build a local blastp database';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`protein_data` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `translate_from_idx` ON `cad_registry`.`protein_data` (`gene_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `protein_model_idx` ON `cad_registry`.`protein_data` (`protein_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `dbname_idx` ON `cad_registry`.`protein_data` (`source_db` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `pdb_datavalue_idx` ON `cad_registry`.`protein_data` (`pdb_data` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`protein_ontology`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`protein_ontology` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`protein_ontology` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `protein_id` INT UNSIGNED NOT NULL,
  `ontology_id` INT UNSIGNED NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `protein_data`
    FOREIGN KEY (`protein_id`)
    REFERENCES `cad_registry`.`protein_data` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ontology_term`
    FOREIGN KEY (`ontology_id`)
    REFERENCES `cad_registry`.`ontology` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`protein_ontology` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `protein_data_idx` ON `cad_registry`.`protein_ontology` (`protein_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `ontology_term_idx` ON `cad_registry`.`protein_ontology` (`ontology_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `unique_features` ON `cad_registry`.`protein_ontology` (`protein_id` ASC, `ontology_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`reaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`reaction` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`reaction` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hashcode` CHAR(32) NULL,
  `name` VARCHAR(1024) NOT NULL COMMENT 'name of this reaction',
  `ec_number` VARCHAR(10) NULL COMMENT 'ec number of this reaction, value could be null(means is a chemical reaction that not required of enzyme)',
  `equation` VARCHAR(4096) NOT NULL COMMENT 'equation string of this reaction',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '[biological process model] biological reaction/chemical reaction model';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`reaction` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE FULLTEXT INDEX `search_text` ON `cad_registry`.`reaction` (`name`, `note`) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `unique_index` ON `cad_registry`.`reaction` (`hashcode` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`registry_resolver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`registry_resolver` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`registry_resolver` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `register_name` VARCHAR(255) NOT NULL COMMENT 'symbol name of the model object',
  `symbol_id` INT UNSIGNED NOT NULL COMMENT 'symbol model table id, could be reference to metabolites, gene, protein, reaction and cellular compartment location table',
  `type` INT UNSIGNED NOT NULL COMMENT 'the symbol model type, reference to vocabulary term table',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `register_namespace`
    FOREIGN KEY (`type`)
    REFERENCES `cad_registry`.`vocabulary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `metabolite_reference`
    FOREIGN KEY (`symbol_id`)
    REFERENCES `cad_registry`.`metabolites` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `gene_reference`
    FOREIGN KEY (`symbol_id`)
    REFERENCES `cad_registry`.`gene` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `protein_reference`
    FOREIGN KEY (`symbol_id`)
    REFERENCES `cad_registry`.`protein` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `reaction_reference`
    FOREIGN KEY (`symbol_id`)
    REFERENCES `cad_registry`.`reaction` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'a unify symbol mapping inside the registry database system';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`registry_resolver` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `register_namespace_idx` ON `cad_registry`.`registry_resolver` (`type` ASC) INVISIBLE;

SHOW WARNINGS;
CREATE INDEX `metabolite_reference_idx` ON `cad_registry`.`registry_resolver` (`symbol_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `find_name` ON `cad_registry`.`registry_resolver` (`register_name` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `register_name_UNIQUE` ON `cad_registry`.`registry_resolver` (`register_name` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`regulatory_network`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`regulatory_network` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`regulatory_network` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `regulator` INT UNSIGNED NOT NULL COMMENT 'TF regulator protein instance',
  `motif_site` INT UNSIGNED NOT NULL COMMENT 'motif site instance',
  `effector` INT UNSIGNED NOT NULL COMMENT 'metabolite effector of the TF, id reference to the metabolites table',
  `effects` DOUBLE NOT NULL COMMENT 'the regulation effects, positive value means activator, negative value means inhibitor',
  `db_source` INT UNSIGNED NOT NULL COMMENT 'database source of this binding relationship',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `db_name`
    FOREIGN KEY (`db_source`)
    REFERENCES `cad_registry`.`vocabulary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `metabolite_info`
    FOREIGN KEY (`effector`)
    REFERENCES `cad_registry`.`metabolites` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `protein_info`
    FOREIGN KEY (`regulator`)
    REFERENCES `cad_registry`.`protein_data` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `motif_site_info`
    FOREIGN KEY (`motif_site`)
    REFERENCES `cad_registry`.`nucleotide_data` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'TF to motif binding relationship';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`regulatory_network` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `motif_site_info_idx` ON `cad_registry`.`regulatory_network` (`motif_site` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `protein_info_idx` ON `cad_registry`.`regulatory_network` (`regulator` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `metabolite_info_idx` ON `cad_registry`.`regulatory_network` (`effector` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `db_name_idx` ON `cad_registry`.`regulatory_network` (`db_source` ASC) VISIBLE;

SHOW WARNINGS;
CREATE FULLTEXT INDEX `search_text` ON `cad_registry`.`regulatory_network` (`note`) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`struct_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`struct_data` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`struct_data` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `metabolite_id` INT UNSIGNED NOT NULL COMMENT 'id reference to the metabolites table',
  `checksum` CHAR(32) NOT NULL COMMENT 'md5 checksum of the smiles string',
  `smiles` LONGTEXT NOT NULL COMMENT 'the molecule structure data in SMILES string format',
  `fingerprint` LONGTEXT NULL COMMENT ' embedding vector of this smiles structure sequence, base64 encoded double array, network byte order',
  `pdb_data` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '3d structre data in pdb format, transform from the SMILES string to pdb data via RDkit software or other program, used for data visualization on web',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  CONSTRAINT `metabolite_info`
    FOREIGN KEY (`metabolite_id`)
    REFERENCES `cad_registry`.`metabolites` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pdb_modelvalue`
    FOREIGN KEY (`pdb_data`)
    REFERENCES `cad_registry`.`pdb` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'the metabolite molecule structre data';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`struct_data` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `metabolite_info_idx` ON `cad_registry`.`struct_data` (`metabolite_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `pdb_modelvalue_idx` ON `cad_registry`.`struct_data` (`pdb_data` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`subcellular_location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`subcellular_location` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`subcellular_location` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `protein_id` INT UNSIGNED NOT NULL COMMENT 'protein object instance id',
  `location_id` INT UNSIGNED NOT NULL COMMENT 'cellular compartment location id',
  `evidence` VARCHAR(1024) NOT NULL COMMENT 'usually be the article doi id or pubmed id',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `compartment_term`
    FOREIGN KEY (`location_id`)
    REFERENCES `cad_registry`.`compartment_location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `prot_obj`
    FOREIGN KEY (`protein_id`)
    REFERENCES `cad_registry`.`protein_data` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`subcellular_location` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `compartment_term_idx` ON `cad_registry`.`subcellular_location` (`location_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `prot_obj_idx` ON `cad_registry`.`subcellular_location` (`protein_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`synonym`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`synonym` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`synonym` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `obj_id` INT UNSIGNED NOT NULL COMMENT 'object reference id to the metabolites/genes/protein/compartment location/reaction table',
  `type` INT UNSIGNED NOT NULL COMMENT 'entity type of the object that associated with this synonym name',
  `db_source` INT UNSIGNED NOT NULL COMMENT 'database source of this synonym name',
  `synonym` LONGTEXT NOT NULL COMMENT 'synonym name',
  `hashcode` CHAR(32) NOT NULL COMMENT 'md5 checksum of the tolower( synonym field)',
  `lang` VARCHAR(8) NOT NULL COMMENT 'language of this name, default is \'en\' english, value could be en - english, zh - chinese',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  CONSTRAINT `dbname`
    FOREIGN KEY (`db_source`)
    REFERENCES `cad_registry`.`vocabulary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `entity_namespace`
    FOREIGN KEY (`type`)
    REFERENCES `cad_registry`.`vocabulary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `entity_metabolite`
    FOREIGN KEY (`obj_id`)
    REFERENCES `cad_registry`.`metabolites` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `entity_gene`
    FOREIGN KEY (`obj_id`)
    REFERENCES `cad_registry`.`gene` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `entity_protein`
    FOREIGN KEY (`obj_id`)
    REFERENCES `cad_registry`.`protein` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `entity_location`
    FOREIGN KEY (`obj_id`)
    REFERENCES `cad_registry`.`compartment_location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `entity_reaction`
    FOREIGN KEY (`obj_id`)
    REFERENCES `cad_registry`.`reaction` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'synonyms, alias names of the model objects';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`synonym` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `dbname_idx` ON `cad_registry`.`synonym` (`db_source` ASC) INVISIBLE;

SHOW WARNINGS;
CREATE INDEX `entity_namespace_idx` ON `cad_registry`.`synonym` (`type` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `entity_metabolite_idx` ON `cad_registry`.`synonym` (`obj_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `find_name` ON `cad_registry`.`synonym` (`lang` ASC, `hashcode` ASC) INVISIBLE;

SHOW WARNINGS;
CREATE FULLTEXT INDEX `search_text` ON `cad_registry`.`synonym` (`synonym`) INVISIBLE;

SHOW WARNINGS;
CREATE INDEX `fast_hash_search` ON `cad_registry`.`synonym` (`obj_id` ASC, `hashcode` ASC, `type` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `unique_name` ON `cad_registry`.`synonym` (`obj_id` ASC, `type` ASC, `db_source` ASC, `hashcode` ASC, `lang` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`topic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`topic` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`topic` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `topic_id` INT UNSIGNED NOT NULL,
  `model_id` INT UNSIGNED NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `registry_model`
    FOREIGN KEY (`model_id`)
    REFERENCES `cad_registry`.`registry_resolver` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `topic_term`
    FOREIGN KEY (`topic_id`)
    REFERENCES `cad_registry`.`vocabulary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'topic about the biological model';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`topic` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `registry_model_idx` ON `cad_registry`.`topic` (`model_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `topic_term_idx` ON `cad_registry`.`topic` (`topic_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `unique_link` ON `cad_registry`.`topic` (`topic_id` ASC, `model_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cad_registry`.`vocabulary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cad_registry`.`vocabulary` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cad_registry`.`vocabulary` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(64) NOT NULL DEFAULT 'NA' COMMENT 'term category name, value could be registry model type, external database, metabolic edge type',
  `term` VARCHAR(255) NOT NULL COMMENT 'vocabulary term',
  `parent_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'ontology parent is of this vocabylary term, reference to the id of another vocabulary term that could be used as the ancestor of this term',
  `color` VARCHAR(8) NOT NULL DEFAULT '#000000' COMMENT 'html color code for make render of this vocabulary term display on web',
  `add_time` DATETIME NOT NULL DEFAULT now(),
  `note` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `ontology_tree`
    FOREIGN KEY (`parent_id`)
    REFERENCES `cad_registry`.`vocabulary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'vocabulary term inside the registry database';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `cad_registry`.`vocabulary` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `ontology_tree_idx` ON `cad_registry`.`vocabulary` (`parent_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `search_term` ON `cad_registry`.`vocabulary` (`category` ASC, `term` ASC) INVISIBLE;

SHOW WARNINGS;
CREATE FULLTEXT INDEX `search_text` ON `cad_registry`.`vocabulary` (`note`) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
