.\" man page create by R# package system.
.TH REGISTRY 1 2000-Jan "child_list" "child_list"
.SH NAME
child_list \- 
.SH SYNOPSIS
\fIchild_list(\fBregistry\fR as <generic> biocad_registry, 
\fBtax_id\fR as string, 
\fBdirect_list\fR as boolean = TRUE);\fR
.SH SEE ALSO
registry
.SH FILES
.PP
biocad_registry.dll
.PP
