.\" man page create by R# package system.
.TH REGISTRY 1 2000-Jan "get_by_xref" "get_by_xref"
.SH NAME
get_by_xref \- 
.SH SYNOPSIS
\fIget_by_xref(\fBregistry\fR as <generic> biocad_registry, 
\fBid\fR as string, 
\fBdbname\fR as string = \fB<NULL>\fR);\fR
.SH SEE ALSO
registry
.SH FILES
.PP
biocad_registry.dll
.PP
