.\" man page create by R# package system.
.TH REGISTRY 1 2000-1月 "imports_metab_repo" "imports_metab_repo"
.SH NAME
imports_metab_repo \- a general function for make metabolites data imports
.SH SYNOPSIS
\fIimports_metab_repo(\fBregistry\fR as <generic> biocad_registry, 
\fBmetab\fR as any, 
\fBdb_name\fR as string, 
\fBcheck_id\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
a general function for make metabolites data imports
.PP
.SH OPTIONS
.PP
\fBregistry\fB \fR\- -. 
.PP
.PP
\fBmetab\fB \fR\- -. 
.PP
.PP
\fBdb_name\fB \fR\- -. 
.PP
.PP
\fBcheck_id\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
registry
.SH FILES
.PP
biocad_registry.dll
.PP
