.\" man page create by R# package system.
.TH REGISTRY 1 2000-Jan "imports_mona" "imports_mona"
.SH NAME
imports_mona \- 
.SH SYNOPSIS
\fIimports_mona(\fBregistry\fR as <generic> biocad_registry, 
\fBmona\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
registry
.SH FILES
.PP
biocad_registry.dll
.PP
