.\" man page create by R# package system.
.TH REGISTRY 1 2000-Jan "imports_spectraverse" "imports_spectraverse"
.SH NAME
imports_spectraverse \- 
.SH SYNOPSIS
\fIimports_spectraverse(\fBregistry\fR as <generic> biocad_registry, 
\fBspectraverse\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
registry
.SH FILES
.PP
biocad_registry.dll
.PP
