.\" man page create by R# package system.
.TH REGISTRY 1 2000-1月 "imports_struct_domains" "imports_struct_domains"
.SH NAME
imports_struct_domains \- 
.SH SYNOPSIS
\fIimports_struct_domains(\fBregistry\fR as <generic> biocad_registry, 
\fBuniprot\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
registry
.SH FILES
.PP
biocad_registry.dll
.PP
