.\" man page create by R# package system.
.TH REGISTRY 1 2000-1月 "imports_planttfdb" "imports_planttfdb"
.SH NAME
imports_planttfdb \- 
.SH SYNOPSIS
\fIimports_planttfdb(\fBregistry\fR as <generic> biocad_registry, 
\fBmotifs\fR as any, 
\fBtf\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
registry
.SH FILES
.PP
biocad_registry.dll
.PP
