.\" man page create by R# package system.
.TH REGISTRY 1 2000-1月 "imports_sbml_reactions" "imports_sbml_reactions"
.SH NAME
imports_sbml_reactions \- 
.SH SYNOPSIS
\fIimports_sbml_reactions(\fBregistry\fR as <generic> biocad_registry, 
\fBsbml\fR as <generic> XmlFile`1, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
registry
.SH FILES
.PP
biocad_registry.dll
.PP
