.\" man page create by R# package system.
.TH REGISTRY 1 2000-1月 "imports_planttfdb" "imports_planttfdb"
.SH NAME
imports_planttfdb \- 
.SH SYNOPSIS
\fIimports_planttfdb(\fBregistry\fR as <generic> biocad_registry, 
\fBmotifs\fR as any, 
\fBtf\fR as any, 
\fBtaxname\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBregistry\fB \fR\- -. 
.PP
.PP
\fBmotifs\fB \fR\- -. 
.PP
.PP
\fBtf\fB \fR\- PlantTFDB TF fasta sequence collection. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
registry
.SH FILES
.PP
biocad_registry.dll
.PP
