.\" man page create by R# package system.
.TH REGISTRY 1 2000-Jan "imports_kegg_reactions" "imports_kegg_reactions"
.SH NAME
imports_kegg_reactions \- 
.SH SYNOPSIS
\fIimports_kegg_reactions(\fBregistry\fR as <generic> biocad_registry, 
\fBkegg\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
registry
.SH FILES
.PP
biocad_registry.dll
.PP
