.\" man page create by R# package system.
.TH REGISTRY 1 2000-Jan "imports_pubchem" "imports_pubchem"
.SH NAME
imports_pubchem \- 
.SH SYNOPSIS
\fIimports_pubchem(\fBregistry\fR as <generic> biocad_registry, 
\fBpubchem\fR as any, 
\fBskip_prefix\fR as integer = 0, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
registry
.SH FILES
.PP
biocad_registry.dll
.PP
