.\" man page create by R# package system.
.TH REGISTRY 1 2000-Jan "imports_metacyc_compounds" "imports_metacyc_compounds"
.SH NAME
imports_metacyc_compounds \- 
.SH SYNOPSIS
\fIimports_metacyc_compounds(\fBregistry\fR as <generic> biocad_registry, 
\fBmetacyc\fR as <generic> Workspace);\fR
.SH SEE ALSO
registry
.SH FILES
.PP
biocad_registry.dll
.PP
