.\" man page create by R# package system.
.TH REGISTRY 1 2000-1月 "import_refseq" "import_refseq"
.SH NAME
import_refseq \- 
.SH SYNOPSIS
\fIimport_refseq(\fBregistry\fR as <generic> biocad_registry, 
\fBrefseq\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
registry
.SH FILES
.PP
biocad_registry.dll
.PP
