.\" man page create by R# package system.
.TH REGISTRY 1 2000-1月 "import_brenda_enzymes" "import_brenda_enzymes"
.SH NAME
import_brenda_enzymes \- 
.SH SYNOPSIS
\fIimport_brenda_enzymes(\fBregistry\fR as <generic> biocad_registry, 
\fBbrenda\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
registry
.SH FILES
.PP
biocad_registry.dll
.PP
