.\" man page create by R# package system.
.TH REGISTRY 1 2000-Jan "make_genbank_dbxrefs" "make_genbank_dbxrefs"
.SH NAME
make_genbank_dbxrefs \- 
.SH SYNOPSIS
\fImake_genbank_dbxrefs(\fBregistry\fR as <generic> biocad_registry, 
\fBgenbank\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
registry
.SH FILES
.PP
biocad_registry.dll
.PP
