.\" man page create by R# package system.
.TH REGISTRY 1 2000-1月 "metabolite_translation" "metabolite_translation"
.SH NAME
metabolite_translation \- 
.SH SYNOPSIS
\fImetabolite_translation(\fBregistry\fR as <generic> biocad_registry, 
\fBontology\fR as string);\fR
.SH SEE ALSO
registry
.SH FILES
.PP
biocad_registry.dll
.PP
