.\" man page create by R# package system.
.TH REGISTRY 1 2000-1月 "ontology_translation" "ontology_translation"
.SH NAME
ontology_translation \- 
.SH SYNOPSIS
\fIontology_translation(\fBregistry\fR as <generic> biocad_registry, 
\fBontology\fR as string);\fR
.SH SEE ALSO
registry
.SH FILES
.PP
biocad_registry.dll
.PP
