.\" man page create by R# package system.
.TH REGISTRY 1 2000-Jan "save_genbank" "save_genbank"
.SH NAME
save_genbank \- 
.SH SYNOPSIS
\fIsave_genbank(\fBregistry\fR as <generic> biocad_registry, 
\fBgenbank\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
registry
.SH FILES
.PP
biocad_registry.dll
.PP
