.\" man page create by R# package system.
.TH REGISTRY 1 2000-Jan "save_TRN" "save_TRN"
.SH NAME
save_TRN \- Save RegPrecise regulation network
.SH SYNOPSIS
\fIsave_TRN(\fBregistry\fR as <generic> biocad_registry, 
\fBgenomes\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Save RegPrecise regulation network
.PP
.SH OPTIONS
.PP
\fBregistry\fB \fR\- -. 
.PP
.PP
\fBgenomes\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
registry
.SH FILES
.PP
biocad_registry.dll
.PP
