.\" man page create by R# package system.
.TH REGISTRY 1 2000-Jan "taxonomy_lineage" "taxonomy_lineage"
.SH NAME
taxonomy_lineage \- 
.SH SYNOPSIS
\fItaxonomy_lineage(\fBregistry\fR as <generic> biocad_registry, 
\fBtax_id\fR as string);\fR
.SH SEE ALSO
registry
.SH FILES
.PP
biocad_registry.dll
.PP
