Imports Oracle.LinuxCompatibility.MySQL
Imports Oracle.LinuxCompatibility.MySQL.MySqlBuilder
Imports Oracle.LinuxCompatibility.MySQL.Uri

Namespace biocad_registryModel

Public MustInherit Class db_mysql : Inherits IDatabase
Protected ReadOnly m_compartment_location As TableModel(Of compartment_location)
Protected ReadOnly m_complex As TableModel(Of complex)
Protected ReadOnly m_conserved_operon As TableModel(Of conserved_operon)
Protected ReadOnly m_db_xrefs As TableModel(Of db_xrefs)
Protected ReadOnly m_gene As TableModel(Of gene)
Protected ReadOnly m_gene_ontology As TableModel(Of gene_ontology)
Protected ReadOnly m_kinetics_law As TableModel(Of kinetics_law)
Protected ReadOnly m_metabolic_network As TableModel(Of metabolic_network)
Protected ReadOnly m_metabolite_class As TableModel(Of metabolite_class)
Protected ReadOnly m_metabolites As TableModel(Of metabolites)
Protected ReadOnly m_molecular_networking As TableModel(Of molecular_networking)
Protected ReadOnly m_motif As TableModel(Of motif)
Protected ReadOnly m_ncbi_taxonomy As TableModel(Of ncbi_taxonomy)
Protected ReadOnly m_nucleotide_data As TableModel(Of nucleotide_data)
Protected ReadOnly m_ontology As TableModel(Of ontology)
Protected ReadOnly m_ontology_relation As TableModel(Of ontology_relation)
Protected ReadOnly m_operon As TableModel(Of operon)
Protected ReadOnly m_organism_source As TableModel(Of organism_source)
Protected ReadOnly m_pathway_network As TableModel(Of pathway_network)
Protected ReadOnly m_pathway_view As TableModel(Of pathway_view)
Protected ReadOnly m_pdb As TableModel(Of pdb)
Protected ReadOnly m_protein As TableModel(Of protein)
Protected ReadOnly m_protein_data As TableModel(Of protein_data)
Protected ReadOnly m_protein_ontology As TableModel(Of protein_ontology)
Protected ReadOnly m_reaction As TableModel(Of reaction)
Protected ReadOnly m_registry_resolver As TableModel(Of registry_resolver)
Protected ReadOnly m_regulatory_network As TableModel(Of regulatory_network)
Protected ReadOnly m_struct_data As TableModel(Of struct_data)
Protected ReadOnly m_subcellular_location As TableModel(Of subcellular_location)
Protected ReadOnly m_synonym As TableModel(Of synonym)
Protected ReadOnly m_topic As TableModel(Of topic)
Protected ReadOnly m_vocabulary As TableModel(Of vocabulary)
Protected Sub New(mysqli As ConnectionUri)
Call MyBase.New(mysqli)

Me.m_compartment_location = model(Of compartment_location)()
Me.m_complex = model(Of complex)()
Me.m_conserved_operon = model(Of conserved_operon)()
Me.m_db_xrefs = model(Of db_xrefs)()
Me.m_gene = model(Of gene)()
Me.m_gene_ontology = model(Of gene_ontology)()
Me.m_kinetics_law = model(Of kinetics_law)()
Me.m_metabolic_network = model(Of metabolic_network)()
Me.m_metabolite_class = model(Of metabolite_class)()
Me.m_metabolites = model(Of metabolites)()
Me.m_molecular_networking = model(Of molecular_networking)()
Me.m_motif = model(Of motif)()
Me.m_ncbi_taxonomy = model(Of ncbi_taxonomy)()
Me.m_nucleotide_data = model(Of nucleotide_data)()
Me.m_ontology = model(Of ontology)()
Me.m_ontology_relation = model(Of ontology_relation)()
Me.m_operon = model(Of operon)()
Me.m_organism_source = model(Of organism_source)()
Me.m_pathway_network = model(Of pathway_network)()
Me.m_pathway_view = model(Of pathway_view)()
Me.m_pdb = model(Of pdb)()
Me.m_protein = model(Of protein)()
Me.m_protein_data = model(Of protein_data)()
Me.m_protein_ontology = model(Of protein_ontology)()
Me.m_reaction = model(Of reaction)()
Me.m_registry_resolver = model(Of registry_resolver)()
Me.m_regulatory_network = model(Of regulatory_network)()
Me.m_struct_data = model(Of struct_data)()
Me.m_subcellular_location = model(Of subcellular_location)()
Me.m_synonym = model(Of synonym)()
Me.m_topic = model(Of topic)()
Me.m_vocabulary = model(Of vocabulary)()
End Sub
End Class

End Namespace
