.\" man page create by R# package system.
.TH DATA_EXPORTS 1 2000-Jan "export_topic_structdata" "export_topic_structdata"
.SH NAME
export_topic_structdata \- 
.SH SYNOPSIS
\fIexport_topic_structdata(\fBregistry\fR as <generic> biocad_registry, 
\fBtag_name\fR as string);\fR
.SH SEE ALSO
data_exports
.SH FILES
.PP
biocad_registry.dll
.PP
