.\" man page create by R# package system.
.TH DATA_EXPORTS 1 2000-Jan "export_by_cids" "export_by_cids"
.SH NAME
export_by_cids \- 
.SH SYNOPSIS
\fIexport_by_cids(\fBregistry\fR as <generic> biocad_registry, 
\fBcid\fR as any, 
\fBwrap_tqdm\fR as boolean = TRUE);\fR
.SH SEE ALSO
data_exports
.SH FILES
.PP
biocad_registry.dll
.PP
