.\" man page create by R# package system.
.TH DATA_EXPORTS 1 2000-Jan "export_metabolites" "export_metabolites"
.SH NAME
export_metabolites \- 
.SH SYNOPSIS
\fIexport_metabolites(\fBregistry\fR as <generic> biocad_registry, 
\fBfile\fR as any = \fB<NULL>\fR, 
\fBpage_size\fR as integer = 10000, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
data_exports
.SH FILES
.PP
biocad_registry.dll
.PP
